#%RAML 1.0
title: Indix
version: 2.0.0
baseUri: api.indix.com/
mediaType:
- application/json
uses:
  commons: https://raw.githubusercontent.com/apiregistry/commons/master/commons.raml
  extras: https://raw.githubusercontent.com/apiregistry/typesExtras/master/typeExtras.raml
/v2:
  /brands:
    get:
      description: <p>Lists all brands, along with their IDs, matching query term. Does not support wildcards. Limit is 10 results per query. This API does not consume any credits.
      displayName: 'Search Brands - Lists all brands along with their IDs - Credits:
        ã0'
      queryParameters:
        q:
          type: string
          description: Search term to match against brand name. Partial match. Case insensitive.
          displayName: q
        app_id:
          type: string
          description: Your application id
          displayName: app_id
        app_key:
          type: string
          description: Your application key
          displayName: app_key
      responses:
        200:
          description: Response
  /bulk:
    /ase:
      /{jobId}:
        uriParameters:
          jobId:
            type: string
            description: The id that would be used to query the status of the submitted job and download the final products
            displayName: jobId
        /download:
          get:
            description: API downloads the products as a file. This API does not consume any credits.
            displayName: 'ASE Bulk - Download the products as a file - Credits: ã0'
            queryParameters:
              app_id:
                type: string
                description: Your application id
                displayName: app_id
              app_key:
                type: string
                description: Your application key
                displayName: app_key
            responses:
              200:
                description: Response
        get:
          description: API returns the status  of  the bulk  Job. This API does not consume any credits.
          displayName: 'ASE Bulk - Get job status - Credits: ã0'
          queryParameters:
            app_id:
              type: string
              description: Your application id
              displayName: app_id
            app_key:
              type: string
              description: Your application key
              displayName: app_key
          responses:
            200:
              description: Response
    /jobs:
      /{jobId}:
        uriParameters:
          jobId:
            type: string
            description: The id that would be used to query the status of the submitted job and download the final products
            displayName: jobId
        /download:
          get:
            description: API downloads the products as a file. This API does not consume any credits.
            displayName: 'Bulk - Download the products as a file - Credits: ã0'
            queryParameters:
              app_id:
                type: string
                description: Your application id
                displayName: app_id
              app_key:
                type: string
                description: Your application key
                displayName: app_key
            responses:
              200:
                description: Response
        get:
          description: API returns the status  of  the bulk  Job. This API does not consume any credits.
          displayName: 'Bulk - Get job status - Credits: ã0'
          queryParameters:
            app_id:
              type: string
              description: Your application id
              displayName: app_id
            app_key:
              type: string
              description: Your application key
              displayName: app_key
          responses:
            200:
              description: Response
  /catalogPremium:
    /bulk:
      /lookup:
        post:
          description: This operation returns the catalog premium information for the specified product across all the stores where it is sold at. This consumes 18 credits per product returned.
          displayName: 'Bulk Product Details - Returns catalog premium information
            for a product - Credits: ãn x 18'
          body:
            multipart/form-data:
              type: object
              properties:
                countryCode:
                  type: string
                  description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
                  displayName: countryCode
                file:
                  type: file
                  description: |-
                    File input format: JsonLines. Each line should be a valid json conforming to one of the below formats<br><pre>{"upc": "upc1"}
                    {"mpn": "mpn1", "brandId":  123}
                    {"sku": "mpn1", "storeId":  123}</pre>
                  displayName: file
                app_id:
                  type: string
                  description: Your application id
                  displayName: app_id
                app_key:
                  type: string
                  description: Your application key
                  displayName: app_key
          responses:
            200:
              description: Response
      /products:
        post:
          description: Returns a collection of products matching a specified query, along with a variety of statistics about the query results. Requires at least one of query, url, upc, mpn, sku, brandId, storeId, or categoryId. This consumes 18 credits per product returned.
          displayName: 'Bulk Search Products - Retrieves a list of products matching
            a variety of query parameters with their catalog info across stores -
            Credits: ãn x 18'
          body:
            application/x-www-form-urlencoded:
              type: object
              properties:
                countryCode:
                  type: string
                  description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
                  displayName: countryCode
                storeId?:
                  type: array
                  description: 'Limits results to products sold at store with id.
                    Supports multiple values (acts as OR operator) '
                  displayName: storeId
                  items:
                    type: string
                alsoSoldAt?:
                  type: array
                  description: 'Combined with storeId limits results to products sold
                    at both storeIds and alsoSoldAt storeIds. Supports multiple values
                    (acts as OR operator) '
                  displayName: alsoSoldAt
                  items:
                    type: string
                brandId?:
                  type: array
                  description: Limits results to products of brand with id int.  Supports multiple values (acts as OR operator)
                  displayName: brandId
                  items:
                    type: string
                categoryId?:
                  type: array
                  description: Limits results to products of category with this id. Supports multiple values (acts as OR operator)
                  displayName: categoryId
                  items:
                    type: string
                startPrice?:
                  type: string
                  description: Combined with end_price, limits results to products sold by at least one store at a price between start and end
                  displayName: startPrice
                endPrice?:
                  type: string
                  description: Combined with start_price, limits results to products sold by at least one store at a price between start and end
                  displayName: endPrice
                availability?:
                  type: string
                  description: 'Limits results to either in-stock or out-of-stock
                    items. Accepted values: ''IN_STOCK'',''OUT_OF_STOCK'''
                  displayName: availability
                priceHistoryAvailable?:
                  type: string
                  description: 'Limits results to product that have price history
                    available through the products/{:id}/prices endpoint. Accepted
                    values: ''true'',''false'''
                  displayName: priceHistoryAvailable
                priceChange?:
                  type: string
                  description: 'Limits results to products whose prices have been
                    increased or decreased. Accepted Values: PRICE_INCREASED, PRICE_DECREASED,
                    EITHER'
                  displayName: priceChange
                onPromotion?:
                  type: string
                  description: 'Limits results to products which are on Promotion.
                    Accepted values: ''true'',''false'''
                  displayName: onPromotion
                lastRecordedIn?:
                  type: string
                  description: Limits results to products which have price recorded in the last xx days. Accepted Value is a non-negative integer
                  displayName: lastRecordedIn
                storesCount?:
                  type: string
                  description: Limits results to products with at least a certain number of stores
                  displayName: storesCount
                applyFiltersTo?:
                  type: string
                  description: Specify the stores for which the offer level filter apply. Allowed values - storeId (apply filters to only stores in storeId), alsoSoldAt (apply filters to only stores in alsoSoldAt), storeIdOrAlsoSoldAt (apply filters to stores present in both storeId and alsoSoldAt), any (apply filters across all offers)
                  displayName: applyFiltersTo
                selectOffersFrom?:
                  type: string
                  description: Specify the stores for which offers will be returned in the response. Allowed values - storeId (select offers matching filters from storeId), alsoSoldAt (select offers matching filters from alsoSoldAt), storeIdAndAlsoSoldAt (select offers matching filters from stores in both storeId and alsoSoldAt), all (select all offers irrespective of matching or storeId or alsoSoldAt data)
                  displayName: selectOffersFrom
                app_id:
                  type: string
                  description: Your application id
                  displayName: app_id
                app_key:
                  type: string
                  description: Your application key
                  displayName: app_key
          responses:
            200:
              description: Response
    /products:
      /{mpid}:
        uriParameters:
          mpid:
            type: string
            description: The Indix product identifier - should be a 32-digit HEX value retrieved via the Product Search API
            displayName: mpid
        get:
          description: <p>This operation returns the catalog premium information for the specified product across all the stores where it is sold at. This consumes 18 credits.
          displayName: 'Product Details - Returns catalog premium information for
            a product - Credits: ã18'
          queryParameters:
            countryCode:
              type: string
              description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
              displayName: countryCode
            pageNumber?:
              type: string
              description: The page number of the result set to return. 50 results per page, plus similar items
              displayName: pageNumber
            app_id:
              type: string
              description: Your application id
              displayName: app_id
            app_key:
              type: string
              description: Your application key
              displayName: app_key
          responses:
            200:
              description: Response
      get:
        description: <p>Returns a collection of products matching a specified query, along with a variety of statistics about the query results. Requires at least one of query, url, upc, mpn, sku, brandId, storeId, or categoryId. This consumes 18 credits per product returned.
        displayName: 'Search Products - Retrieves a list of products matching a variety
          of query parameters with their catalog info across stores - Credits: ãn
          x 18'
        queryParameters:
          countryCode:
            type: string
            description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
            displayName: countryCode
          q?:
            type: string
            description: The product search term
            displayName: q
          storeId?:
            type: array
            description: 'Limits results to products sold at store with id. Supports
              multiple values (acts as OR operator) '
            displayName: storeId
            items:
              type: string
          alsoSoldAt?:
            type: array
            description: 'Combined with storeId limits results to products sold at
              both storeIds and alsoSoldAt storeIds. Supports multiple values (acts
              as OR operator) '
            displayName: alsoSoldAt
            items:
              type: string
          brandId?:
            type: array
            description: Limits results to products of brand with id int. Supports multiple values (acts as OR operator)
            displayName: brandId
            items:
              type: string
          categoryId?:
            type: array
            description: Limits results to products of category with this id. Supports multiple values (acts as OR operator)
            displayName: categoryId
            items:
              type: string
          url?:
            type: string
            description: Search by product URL
            displayName: url
          upc?:
            type: string
            description: Limit results to products with this UPC
            displayName: upc
          mpn?:
            type: string
            description: Limit results to products with this MPN
            displayName: mpn
          sku?:
            type: string
            description: Limit results to products with this SKU
            displayName: sku
          startPrice?:
            type: string
            description: Combined with end_price, limits results to products sold by at least one store at a price between start and end
            displayName: startPrice
          endPrice?:
            type: string
            description: Combined with start_price, limits results to products sold by at least one store at a price between start and end
            displayName: endPrice
          availability?:
            type: string
            description: 'Limits results to either in-stock or out-of-stock items.
              Accepted values: ''IN_STOCK'',''OUT_OF_STOCK'''
            displayName: availability
          priceHistoryAvailable?:
            type: string
            description: 'Limits results to product that have price history available
              through the products/{:id}/prices endpoint. Accepted values: ''true'',''false'''
            displayName: priceHistoryAvailable
          priceChange?:
            type: string
            description: 'Limits results to products whose prices have been increased
              or decreased. Accepted Values: PRICE_INCREASED, PRICE_DECREASED, EITHER'
            displayName: priceChange
          onPromotion?:
            type: string
            description: 'Limits results to products which are on Promotion. Accepted
              values: ''true'',''false'''
            displayName: onPromotion
          lastRecordedIn?:
            type: string
            description: Limits results to products which have price recorded in the last xx days. Accepted Value is a non-negative integer
            displayName: lastRecordedIn
          storesCount?:
            type: string
            description: Limits results to products with at least a certain number of stores
            displayName: storesCount
          applyFiltersTo?:
            type: string
            description: Specify the stores for which the offer level filter apply. Allowed values - storeId (apply filters to only stores in storeId), alsoSoldAt (apply filters to only stores in alsoSoldAt), storeIdOrAlsoSoldAt (apply filters to stores present in both storeId and alsoSoldAt), any (apply filters across all offers)
            displayName: applyFiltersTo
          selectOffersFrom?:
            type: string
            description: Specify the stores for which offers will be returned in the response. Allowed values - storeId (select offers matching filters from storeId), alsoSoldAt (select offers matching filters from alsoSoldAt), storeIdAndAlsoSoldAt (select offers matching filters from stores in both storeId and alsoSoldAt), all (select all offers irrespective of matching or storeId or alsoSoldAt data)
            displayName: selectOffersFrom
          sortBy?:
            type: string
            description: Sort by values - PRICE_LOW_TO_HIGH, PRICE_HIGH_TO_LOW, MOST_RECENT.
            displayName: sortBy
          facetBy?:
            type: array
            description: Facet by values - storeId, brandId, categoryId. Should be a comma separated list of allowed values.
            displayName: facetBy
            items:
              type: string
          pageNumber?:
            type: string
            description: The page number of the result set to return. 10 results per page.
            displayName: pageNumber
          pageSize?:
            type: string
            description: Number of results per page. Allowed values - 10, 20, 50.
            displayName: pageSize
          app_id:
            type: string
            description: Your application id
            displayName: app_id
          app_key:
            type: string
            description: Your application key
            displayName: app_key
        responses:
          200:
            description: Response
  /catalogStandard:
    /bulk:
      /lookup:
        post:
          description: This operation returns the catalog standard information for the specified product across all the stores where it is sold at. This consumes 18 credits per product returned.
          displayName: 'Bulk Product Details - Returns catalog standard information
            for a product - Credits: ãn x 18'
          body:
            multipart/form-data:
              type: object
              properties:
                countryCode:
                  type: string
                  description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
                  displayName: countryCode
                file:
                  type: file
                  description: |-
                    File input format: JsonLines. Each line should be a valid json conforming to one of the below formats<br><pre>{"upc": "upc1"}
                    {"mpn": "mpn1", "brandId":  123}
                    {"sku": "mpn1", "storeId":  123}</pre>
                  displayName: file
                app_id:
                  type: string
                  description: Your application id
                  displayName: app_id
                app_key:
                  type: string
                  description: Your application key
                  displayName: app_key
          responses:
            200:
              description: Response
      /products:
        post:
          description: Returns a collection of products matching a specified query, along with a variety of statistics about the query results. Requires at least one of query, url, upc, mpn, sku, brandId, storeId, or categoryId. This consumes 18 credits per product returned.
          displayName: 'Bulk Search Products - Retrieves a list of products matching
            a variety of query parameters with their aggregated catalog info - Credits:
            ãn x 18'
          body:
            application/x-www-form-urlencoded:
              type: object
              properties:
                countryCode:
                  type: string
                  description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
                  displayName: countryCode
                storeId?:
                  type: array
                  description: 'Limits results to products sold at store with id.
                    Supports multiple values (acts as OR operator) '
                  displayName: storeId
                  items:
                    type: string
                alsoSoldAt?:
                  type: array
                  description: 'Combined with storeId limits results to products sold
                    at both storeIds and alsoSoldAt storeIds. Supports multiple values
                    (acts as OR operator) '
                  displayName: alsoSoldAt
                  items:
                    type: string
                brandId?:
                  type: array
                  description: Limits results to products of brand with id int.  Supports multiple values (acts as OR operator)
                  displayName: brandId
                  items:
                    type: string
                categoryId?:
                  type: array
                  description: Limits results to products of category with this id. Supports multiple values (acts as OR operator)
                  displayName: categoryId
                  items:
                    type: string
                startPrice?:
                  type: string
                  description: Combined with end_price, limits results to products sold by at least one store at a price between start and end
                  displayName: startPrice
                endPrice?:
                  type: string
                  description: Combined with start_price, limits results to products sold by at least one store at a price between start and end
                  displayName: endPrice
                availability?:
                  type: string
                  description: 'Limits results to either in-stock or out-of-stock
                    items. Accepted values: ''IN_STOCK'',''OUT_OF_STOCK'''
                  displayName: availability
                priceHistoryAvailable?:
                  type: string
                  description: 'Limits results to product that have price history
                    available through the products/{:id}/prices endpoint. Accepted
                    values: ''true'',''false'''
                  displayName: priceHistoryAvailable
                priceChange?:
                  type: string
                  description: 'Limits results to products whose prices have been
                    increased or decreased. Accepted Values: PRICE_INCREASED, PRICE_DECREASED,
                    EITHER'
                  displayName: priceChange
                onPromotion?:
                  type: string
                  description: 'Limits results to products which are on Promotion.
                    Accepted values: ''true'',''false'''
                  displayName: onPromotion
                lastRecordedIn?:
                  type: string
                  description: Limits results to products which have price recorded in the last xx days. Accepted Value is a non-negative integer
                  displayName: lastRecordedIn
                storesCount?:
                  type: string
                  description: Limits results to products with at least a certain number of stores
                  displayName: storesCount
                applyFiltersTo?:
                  type: string
                  description: Specify the stores for which the offer level filter apply. Allowed values - storeId (apply filters to only stores in storeId), alsoSoldAt (apply filters to only stores in alsoSoldAt), storeIdOrAlsoSoldAt (apply filters to stores present in both storeId and alsoSoldAt), any (apply filters across all offers)
                  displayName: applyFiltersTo
                selectOffersFrom?:
                  type: string
                  description: Specify the stores for which offers will be returned in the response. Allowed values - storeId (select offers matching filters from storeId), alsoSoldAt (select offers matching filters from alsoSoldAt), storeIdAndAlsoSoldAt (select offers matching filters from stores in both storeId and alsoSoldAt), all (select all offers irrespective of matching or storeId or alsoSoldAt data)
                  displayName: selectOffersFrom
                app_id:
                  type: string
                  description: Your application id
                  displayName: app_id
                app_key:
                  type: string
                  description: Your application key
                  displayName: app_key
          responses:
            200:
              description: Response
    /products:
      /{mpid}:
        uriParameters:
          mpid:
            type: string
            description: The Indix product identifier - should be a 32-digit HEX value retrieved via the Product Search API
            displayName: mpid
        get:
          description: <p>This operation returns the catalog standard information for the specified product across all the stores where it is sold at. This consumes 18 credits.
          displayName: 'Product Details - Returns catalog standard information for
            a product - Credits: ã18'
          queryParameters:
            countryCode:
              type: string
              description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
              displayName: countryCode
            pageNumber?:
              type: string
              description: The page number of the result set to return. 50 results per page, plus similar items
              displayName: pageNumber
            app_id:
              type: string
              description: Your application id
              displayName: app_id
            app_key:
              type: string
              description: Your application key
              displayName: app_key
          responses:
            200:
              description: Response
      get:
        description: <p>Returns a collection of products matching a specified query, along with a variety of statistics about the query results. Requires at least one of query, url, upc, mpn, sku, brandId, storeId, or categoryId. This consumes 18 credits per product returned.
        displayName: 'Search Products - Retrieves a list of products matching a variety
          of query parameters with their aggregated catalog info - Credits: ãn x 18'
        queryParameters:
          countryCode:
            type: string
            description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
            displayName: countryCode
          q?:
            type: string
            description: The product search term
            displayName: q
          storeId?:
            type: array
            description: 'Limits results to products sold at store with id. Supports
              multiple values (acts as OR operator) '
            displayName: storeId
            items:
              type: string
          alsoSoldAt?:
            type: array
            description: 'Combined with storeId limits results to products sold at
              both storeIds and alsoSoldAt storeIds. Supports multiple values (acts
              as OR operator) '
            displayName: alsoSoldAt
            items:
              type: string
          brandId?:
            type: array
            description: Limits results to products of brand with id int.  Supports multiple values (acts as OR operator)
            displayName: brandId
            items:
              type: string
          categoryId?:
            type: array
            description: Limits results to products of category with this id. Supports multiple values (acts as OR operator)
            displayName: categoryId
            items:
              type: string
          url?:
            type: string
            description: Search by product URL
            displayName: url
          upc?:
            type: string
            description: Limit results to products with this UPC
            displayName: upc
          mpn?:
            type: string
            description: Limit results to products with this MPN
            displayName: mpn
          sku?:
            type: string
            description: Limit results to products with this SKU
            displayName: sku
          startPrice?:
            type: string
            description: Combined with end_price, limits results to products sold by at least one store at a price between start and end
            displayName: startPrice
          endPrice?:
            type: string
            description: Combined with start_price, limits results to products sold by at least one store at a price between start and end
            displayName: endPrice
          availability?:
            type: string
            description: 'Limits results to either in-stock or out-of-stock items.
              Accepted values: ''IN_STOCK'',''OUT_OF_STOCK'''
            displayName: availability
          priceHistoryAvailable?:
            type: string
            description: 'Limits results to product that have price history available
              through the products/{:id}/prices endpoint. Accepted values: ''true'',''false'''
            displayName: priceHistoryAvailable
          priceChange?:
            type: string
            description: 'Limits results to products whose prices have been increased
              or decreased. Accepted Values: PRICE_INCREASED, PRICE_DECREASED, EITHER'
            displayName: priceChange
          onPromotion?:
            type: string
            description: 'Limits results to products which are on Promotion. Accepted
              values: ''true'',''false'''
            displayName: onPromotion
          lastRecordedIn?:
            type: string
            description: Limits results to products which have price recorded in the last xx days. Accepted Value is a non-negative integer
            displayName: lastRecordedIn
          storesCount?:
            type: string
            description: Limits results to products with at least a certain number of stores
            displayName: storesCount
          applyFiltersTo?:
            type: string
            description: Specify the stores for which the offer level filter apply. Allowed values - storeId (apply filters to only stores in storeId), alsoSoldAt (apply filters to only stores in alsoSoldAt), storeIdOrAlsoSoldAt (apply filters to stores present in both storeId and alsoSoldAt), any (apply filters across all offers)
            displayName: applyFiltersTo
          selectOffersFrom?:
            type: string
            description: Specify the stores for which offers will be returned in the response. Allowed values - storeId (select offers matching filters from storeId), alsoSoldAt (select offers matching filters from alsoSoldAt), storeIdAndAlsoSoldAt (select offers matching filters from stores in both storeId and alsoSoldAt), all (select all offers irrespective of matching or storeId or alsoSoldAt data)
            displayName: selectOffersFrom
          sortBy?:
            type: string
            description: Sort by values - PRICE_LOW_TO_HIGH, PRICE_HIGH_TO_LOW, MOST_RECENT.
            displayName: sortBy
          facetBy?:
            type: array
            description: Facet by values - storeId, brandId, categoryId. Should be a comma separated list of allowed values.
            displayName: facetBy
            items:
              type: string
          pageNumber?:
            type: string
            description: The page number of the result set to return. 10 results per page.
            displayName: pageNumber
          pageSize?:
            type: string
            description: Number of results per page. Allowed values - 10, 20, 50.
            displayName: pageSize
          app_id:
            type: string
            description: Your application id
            displayName: app_id
          app_key:
            type: string
            description: Your application key
            displayName: app_key
        responses:
          200:
            description: Response
  /categories:
    get:
      description: <p>Lists all categories along with their IDs and ancestry. This API does not consume any credits.
      displayName: 'Export Categories - Lists all categories along with their IDs
        and path - Credits: ã0'
      queryParameters:
        app_id:
          type: string
          description: Your application id
          displayName: app_id
        app_key:
          type: string
          description: Your application key
          displayName: app_key
      responses:
        200:
          description: Response
  /offersPremium:
    /bulk:
      /lookup:
        post:
          description: This operation returns the offers premium information for the specified product across all the stores where it is sold at. This consumes 4 credits per product returned.
          displayName: 'Bulk Product Details - Returns offers premium information
            for a product - Credits: ãn x 4'
          body:
            multipart/form-data:
              type: object
              properties:
                countryCode:
                  type: string
                  description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
                  displayName: countryCode
                file:
                  type: file
                  description: |-
                    File input format: JsonLines. Each line should be a valid json conforming to one of the below formats<br><pre>{"upc": "upc1"}
                    {"mpn": "mpn1", "brandId":  123}
                    {"sku": "mpn1", "storeId":  123}</pre>
                  displayName: file
                app_id:
                  type: string
                  description: Your application id
                  displayName: app_id
                app_key:
                  type: string
                  description: Your application key
                  displayName: app_key
          responses:
            200:
              description: Response
      /products:
        post:
          description: Returns a collection of products matching a specified query, along with a variety of statistics about the query results. Requires at least one of query, url, upc, mpn, sku, brandId, storeId, or categoryId. This consumes 4 credits per product returned.
          displayName: 'Bulk Search Products - Retrieves a list of products matching
            a variety of query parameters with offers info across stores - Credits:
            ãn x 4'
          body:
            application/x-www-form-urlencoded:
              type: object
              properties:
                countryCode:
                  type: string
                  description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
                  displayName: countryCode
                storeId?:
                  type: array
                  description: 'Limits results to products sold at store with id.
                    Supports multiple values (acts as OR operator) '
                  displayName: storeId
                  items:
                    type: string
                alsoSoldAt?:
                  type: array
                  description: 'Combined with storeId limits results to products sold
                    at both storeIds and alsoSoldAt storeIds. Supports multiple values
                    (acts as OR operator) '
                  displayName: alsoSoldAt
                  items:
                    type: string
                brandId?:
                  type: array
                  description: Limits results to products of brand with id int.  Supports multiple values (acts as OR operator)
                  displayName: brandId
                  items:
                    type: string
                categoryId?:
                  type: array
                  description: Limits results to products of category with this id. Supports multiple values (acts as OR operator)
                  displayName: categoryId
                  items:
                    type: string
                startPrice?:
                  type: string
                  description: Combined with end_price, limits results to products sold by at least one store at a price between start and end
                  displayName: startPrice
                endPrice?:
                  type: string
                  description: Combined with start_price, limits results to products sold by at least one store at a price between start and end
                  displayName: endPrice
                availability?:
                  type: string
                  description: 'Limits results to either in-stock or out-of-stock
                    items. Accepted values: ''IN_STOCK'',''OUT_OF_STOCK'''
                  displayName: availability
                priceHistoryAvailable?:
                  type: string
                  description: 'Limits results to product that have price history
                    available through the products/{:id}/prices endpoint. Accepted
                    values: ''true'',''false'''
                  displayName: priceHistoryAvailable
                priceChange?:
                  type: string
                  description: 'Limits results to products whose prices have been
                    increased or decreased. Accepted Values: PRICE_INCREASED, PRICE_DECREASED,
                    EITHER'
                  displayName: priceChange
                onPromotion?:
                  type: string
                  description: 'Limits results to products which are on Promotion.
                    Accepted values: ''true'',''false'''
                  displayName: onPromotion
                lastRecordedIn?:
                  type: string
                  description: Limits results to products which have price recorded in the last xx days. Accepted Value is a non-negative integer
                  displayName: lastRecordedIn
                storesCount?:
                  type: string
                  description: Limits results to products with at least a certain number of stores
                  displayName: storesCount
                applyFiltersTo?:
                  type: string
                  description: Specify the stores for which the offer level filter apply. Allowed values - storeId (apply filters to only stores in storeId), alsoSoldAt (apply filters to only stores in alsoSoldAt), storeIdOrAlsoSoldAt (apply filters to stores present in both storeId and alsoSoldAt), any (apply filters across all offers)
                  displayName: applyFiltersTo
                selectOffersFrom?:
                  type: string
                  description: Specify the stores for which offers will be returned in the response. Allowed values - storeId (select offers matching filters from storeId), alsoSoldAt (select offers matching filters from alsoSoldAt), storeIdAndAlsoSoldAt (select offers matching filters from stores in both storeId and alsoSoldAt), all (select all offers irrespective of matching or storeId or alsoSoldAt data)
                  displayName: selectOffersFrom
                app_id:
                  type: string
                  description: Your application id
                  displayName: app_id
                app_key:
                  type: string
                  description: Your application key
                  displayName: app_key
          responses:
            200:
              description: Response
    /products:
      /{mpid}:
        uriParameters:
          mpid:
            type: string
            description: The Indix product identifier - should be a 32-digit HEX value retrieved via the Product Search API
            displayName: mpid
        get:
          description: <p>This operation returns the offers premium information for the specified product across all the stores where it is sold at. This consumes 4 credits.
          displayName: 'Product Details - Returns offers premium information for a
            product - Credits: ã4'
          queryParameters:
            countryCode:
              type: string
              description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
              displayName: countryCode
            pageNumber?:
              type: string
              description: The page number of the result set to return. 50 results per page, plus similar items
              displayName: pageNumber
            app_id:
              type: string
              description: Your application id
              displayName: app_id
            app_key:
              type: string
              description: Your application key
              displayName: app_key
          responses:
            200:
              description: Response
      get:
        description: <p>Returns a collection of products matching a specified query, along with a variety of statistics about the query results. Requires at least one of query, url, upc, mpn, sku, brandId, storeId, or categoryId. This consumes 4 credits per product returned.
        displayName: 'Search Products - Retrieves a list of products matching a variety
          of query parameters with offers info across stores - Credits: ãn x 4'
        queryParameters:
          countryCode:
            type: string
            description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
            displayName: countryCode
          q?:
            type: string
            description: The product search term
            displayName: q
          storeId?:
            type: array
            description: 'Limits results to products sold at store with id. Supports
              multiple values (acts as OR operator) '
            displayName: storeId
            items:
              type: string
          alsoSoldAt?:
            type: array
            description: 'Combined with storeId limits results to products sold at
              both storeIds and alsoSoldAt storeIds. Supports multiple values (acts
              as OR operator) '
            displayName: alsoSoldAt
            items:
              type: string
          brandId?:
            type: array
            description: Limits results to products of brand with id int.  Supports multiple values (acts as OR operator
            displayName: brandId
            items:
              type: string
          categoryId?:
            type: array
            description: Limits results to products of category with this id. Supports multiple values (acts as OR operator)
            displayName: categoryId
            items:
              type: string
          url?:
            type: string
            description: Search by product URL
            displayName: url
          upc?:
            type: string
            description: Limit results to products with this UPC
            displayName: upc
          mpn?:
            type: string
            description: Limit results to products with this MPN
            displayName: mpn
          sku?:
            type: string
            description: Limit results to products with this SKU
            displayName: sku
          startPrice?:
            type: string
            description: Combined with end_price, limits results to products sold by at least one store at a price between start and end
            displayName: startPrice
          endPrice?:
            type: string
            description: Combined with start_price, limits results to products sold by at least one store at a price between start and end
            displayName: endPrice
          availability?:
            type: string
            description: 'Limits results to either in-stock or out-of-stock items.
              Accepted values: ''IN_STOCK'',''OUT_OF_STOCK'''
            displayName: availability
          priceHistoryAvailable?:
            type: string
            description: 'Limits results to product that have price history available
              through the products/{:id}/prices endpoint. Accepted values: ''true'',''false'''
            displayName: priceHistoryAvailable
          priceChange?:
            type: string
            description: 'Limits results to products whose prices have been increased
              or decreased. Accepted Values: PRICE_INCREASED, PRICE_DECREASED, EITHER'
            displayName: priceChange
          onPromotion?:
            type: string
            description: 'Limits results to products which are on Promotion. Accepted
              values: ''true'',''false'''
            displayName: onPromotion
          lastRecordedIn?:
            type: string
            description: Limits results to products which have price recorded in the last xx days. Accepted Value is a non-negative integer
            displayName: lastRecordedIn
          storesCount?:
            type: string
            description: Limits results to products with at least a certain number of stores
            displayName: storesCount
          applyFiltersTo?:
            type: string
            description: Specify the stores for which the offer level filter apply. Allowed values - storeId (apply filters to only stores in storeId), alsoSoldAt (apply filters to only stores in alsoSoldAt), storeIdOrAlsoSoldAt (apply filters to stores present in both storeId and alsoSoldAt), any (apply filters across all offers)
            displayName: applyFiltersTo
          selectOffersFrom?:
            type: string
            description: Specify the stores for which offers will be returned in the response. Allowed values - storeId (select offers matching filters from storeId), alsoSoldAt (select offers matching filters from alsoSoldAt), storeIdAndAlsoSoldAt (select offers matching filters from stores in both storeId and alsoSoldAt), all (select all offers irrespective of matching or storeId or alsoSoldAt data)
            displayName: selectOffersFrom
          sortBy?:
            type: string
            description: Sort by values - PRICE_LOW_TO_HIGH, PRICE_HIGH_TO_LOW, MOST_RECENT.
            displayName: sortBy
          facetBy?:
            type: array
            description: Facet by values - storeId, brandId, categoryId. Should be a comma separated list of allowed values.
            displayName: facetBy
            items:
              type: string
          pageNumber?:
            type: string
            description: The page number of the result set to return. 10 results per page.
            displayName: pageNumber
          pageSize?:
            type: string
            description: Number of results per page. Allowed values - 10, 20, 50.
            displayName: pageSize
          app_id:
            type: string
            description: Your application id
            displayName: app_id
          app_key:
            type: string
            description: Your application key
            displayName: app_key
        responses:
          200:
            description: Response
  /offersStandard:
    /bulk:
      /lookup:
        post:
          description: This operation returns the offers standard information for the specified product from a single storeId. This consumes 4 credits per product returned.
          displayName: 'Bulk Product Details - Returns offers standard information
            for a product from a single storeId - Credits: ãn x 4'
          body:
            multipart/form-data:
              type: object
              properties:
                countryCode:
                  type: string
                  description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
                  displayName: countryCode
                file:
                  type: file
                  description: |-
                    File input format: JsonLines. Each line should be a valid json conforming to one of the below formats<br><pre>{"upc": "upc1"}
                    {"mpn": "mpn1", "brandId":  123}
                    {"sku": "mpn1", "storeId":  123}</pre>
                  displayName: file
                app_id:
                  type: string
                  description: Your application id
                  displayName: app_id
                app_key:
                  type: string
                  description: Your application key
                  displayName: app_key
          responses:
            200:
              description: Response
      /products:
        post:
          description: Returns a collection of products matching a specified query, along with a variety of statistics about the query results. Requires at least one of query, url, upc, mpn, sku, brandId, storeId, or categoryId. This consumes 4 credits per product returned.
          displayName: 'Bulk Search Products - Retrieves a list of products matching
            a variety of query parameters with offers info from a store - Credits:
            ãn x 4'
          body:
            application/x-www-form-urlencoded:
              type: object
              properties:
                countryCode:
                  type: string
                  description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
                  displayName: countryCode
                storeId?:
                  type: array
                  description: 'Limits results to products sold at store with id.
                    Supports multiple values (acts as OR operator) '
                  displayName: storeId
                  items:
                    type: string
                alsoSoldAt?:
                  type: array
                  description: 'Combined with storeId limits results to products sold
                    at both storeIds and alsoSoldAt storeIds. Supports multiple values
                    (acts as OR operator) '
                  displayName: alsoSoldAt
                  items:
                    type: string
                brandId?:
                  type: array
                  description: Limits results to products of brand with id int.  Supports multiple values (acts as OR operator)
                  displayName: brandId
                  items:
                    type: string
                categoryId?:
                  type: array
                  description: Limits results to products of category with this id. Supports multiple values (acts as OR operator)
                  displayName: categoryId
                  items:
                    type: string
                startPrice?:
                  type: string
                  description: Combined with end_price, limits results to products sold by at least one store at a price between start and end
                  displayName: startPrice
                endPrice?:
                  type: string
                  description: Combined with start_price, limits results to products sold by at least one store at a price between start and end
                  displayName: endPrice
                availability?:
                  type: string
                  description: 'Limits results to either in-stock or out-of-stock
                    items. Accepted values: ''IN_STOCK'',''OUT_OF_STOCK'''
                  displayName: availability
                priceHistoryAvailable?:
                  type: string
                  description: 'Limits results to product that have price history
                    available through the products/{:id}/prices endpoint. Accepted
                    values: ''true'',''false'''
                  displayName: priceHistoryAvailable
                priceChange?:
                  type: string
                  description: 'Limits results to products whose prices have been
                    increased or decreased. Accepted Values: PRICE_INCREASED, PRICE_DECREASED,
                    EITHER'
                  displayName: priceChange
                onPromotion?:
                  type: string
                  description: 'Limits results to products which are on Promotion.
                    Accepted values: ''true'',''false'''
                  displayName: onPromotion
                lastRecordedIn?:
                  type: string
                  description: Limits results to products which have price recorded in the last xx days. Accepted Value is a non-negative integer
                  displayName: lastRecordedIn
                storesCount?:
                  type: string
                  description: Limits results to products with at least a certain number of stores
                  displayName: storesCount
                applyFiltersTo?:
                  type: string
                  description: Specify the stores for which the offer level filter apply. Allowed values - storeId (apply filters to only stores in storeId), alsoSoldAt (apply filters to only stores in alsoSoldAt), storeIdOrAlsoSoldAt (apply filters to stores present in both storeId and alsoSoldAt), any (apply filters across all offers)
                  displayName: applyFiltersTo
                selectOffersFrom?:
                  type: string
                  description: Specify the stores for which offers will be returned in the response. Allowed values - storeId (select offers matching filters from storeId), alsoSoldAt (select offers matching filters from alsoSoldAt), storeIdAndAlsoSoldAt (select offers matching filters from stores in both storeId and alsoSoldAt), all (select all offers irrespective of matching or storeId or alsoSoldAt data)
                  displayName: selectOffersFrom
                app_id:
                  type: string
                  description: Your application id
                  displayName: app_id
                app_key:
                  type: string
                  description: Your application key
                  displayName: app_key
          responses:
            200:
              description: Response
    /products:
      /{mpid}:
        uriParameters:
          mpid:
            type: string
            description: The Indix product identifier - should be a 32-digit HEX value retrieved via the Product Search API
            displayName: mpid
        get:
          description: <p>This operation returns the offers standard information for the specified product from a single storeId. This consumes 4 credits.
          displayName: 'Product Details - Returns offers standard information for
            a product from a single storeId - Credits: ã4'
          queryParameters:
            countryCode:
              type: string
              description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
              displayName: countryCode
            storeId:
              type: string
              description: Limits results to offers from this store
              displayName: storeId
            pageNumber?:
              type: string
              description: The page number of the result set to return. 50 results per page, plus similar items
              displayName: pageNumber
            app_id:
              type: string
              description: Your application id
              displayName: app_id
            app_key:
              type: string
              description: Your application key
              displayName: app_key
          responses:
            200:
              description: Response
      get:
        description: <p>Returns a collection of products matching a specified query, along with a variety of statistics about the query results. Requires at least one of query, url, upc, mpn, sku, brandId, storeId, or categoryId. This consumes 4 credits per product returned.
        displayName: 'Search Products - Retrieves a list of products matching a variety
          of query parameters with offers info from a store - Credits: ãn x 4'
        queryParameters:
          countryCode:
            type: string
            description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
            displayName: countryCode
          q?:
            type: string
            description: The product search term
            displayName: q
          storeId:
            type: string
            description: Limits results to products sold at store with id.
            displayName: storeId
          alsoSoldAt?:
            type: array
            description: 'Combined with storeId limits results to products sold at
              both storeIds and alsoSoldAt storeIds. Supports multiple values (acts
              as OR operator) '
            displayName: alsoSoldAt
            items:
              type: string
          brandId?:
            type: array
            description: Limits results to products of brand with id int.  Supports multiple values (acts as OR operator
            displayName: brandId
            items:
              type: string
          categoryId?:
            type: array
            description: Limits results to products of category with this id. Support multiple values (acts as OR operator
            displayName: categoryId
            items:
              type: string
          url?:
            type: string
            description: Search by product URL
            displayName: url
          upc?:
            type: string
            description: Limit results to products with this UPC
            displayName: upc
          mpn?:
            type: string
            description: Limit results to products with this MPN
            displayName: mpn
          sku?:
            type: string
            description: Limit results to products with this SKU
            displayName: sku
          startPrice?:
            type: string
            description: Combined with end_price, limits results to products sold by at least one store at a price between start and end
            displayName: startPrice
          endPrice?:
            type: string
            description: Combined with start_price, limits results to products sold by at least one store at a price between start and end
            displayName: endPrice
          availability?:
            type: string
            description: 'Limits results to either in-stock or out-of-stock items.
              Accepted values: ''IN_STOCK'',''OUT_OF_STOCK'''
            displayName: availability
          priceHistoryAvailable?:
            type: string
            description: 'Limits results to product that have price history available
              through the products/{:id}/prices endpoint. Accepted values: ''true'',''false'''
            displayName: priceHistoryAvailable
          priceChange?:
            type: string
            description: 'Limits results to products whose prices have been increased
              or decreased. Accepted Values: PRICE_INCREASED, PRICE_DECREASED, EITHER'
            displayName: priceChange
          onPromotion?:
            type: string
            description: 'Limits results to products which are on Promotion. Accepted
              values: ''true'',''false'''
            displayName: onPromotion
          lastRecordedIn?:
            type: string
            description: Limits results to products which have price recorded in the last xx days. Accepted Value is a non-negative integer
            displayName: lastRecordedIn
          storesCount?:
            type: string
            description: Limits results to products with at least a certain number of stores
            displayName: storesCount
          applyFiltersTo?:
            type: string
            description: Specify the stores for which the offer level filter apply. Allowed values - storeId (apply filters to only stores in storeId), alsoSoldAt (apply filters to only stores in alsoSoldAt), storeIdOrAlsoSoldAt (apply filters to stores present in both storeId and alsoSoldAt), any (apply filters across all offers)
            displayName: applyFiltersTo
          selectOffersFrom?:
            type: string
            description: Specify the stores for which offers will be returned in the response. Allowed values - storeId (select offers matching filters from storeId), alsoSoldAt (select offers matching filters from alsoSoldAt), storeIdAndAlsoSoldAt (select offers matching filters from stores in both storeId and alsoSoldAt), all (select all offers irrespective of matching or storeId or alsoSoldAt data)
            displayName: selectOffersFrom
          sortBy?:
            type: string
            description: Sort by values - PRICE_LOW_TO_HIGH, PRICE_HIGH_TO_LOW, MOST_RECENT.
            displayName: sortBy
          facetBy?:
            type: array
            description: Facet by values - storeId, brandId, categoryId. Should be a comma separated list of allowed values.
            displayName: facetBy
            items:
              type: string
          pageNumber?:
            type: string
            description: The page number of the result set to return. 10 results per page.
            displayName: pageNumber
          pageSize?:
            type: string
            description: Number of results per page. Allowed values - 10, 20, 50.
            displayName: pageSize
          app_id:
            type: string
            description: Your application id
            displayName: app_id
          app_key:
            type: string
            description: Your application key
            displayName: app_key
        responses:
          200:
            description: Response
  /products:
    /suggestions:
      get:
        description: <p>Lists all search suggestions matching the query term. Does not support wildcards. Limit 100 results per query. This API does not consume any credits.
        displayName: 'Search Suggestions - Lists all product search suggestions -
          Credits: ã0'
        queryParameters:
          countryCode:
            type: string
            description: Limits results to products of the geography with this code.
            displayName: countryCode
          q:
            type: string
            description: Query term for which suggestions are to be provided
            displayName: q
          app_id:
            type: string
            description: Your application id
            displayName: app_id
          app_key:
            type: string
            description: Your application key
            displayName: app_key
        responses:
          200:
            description: Response
  /stores:
    get:
      description: <p>Lists all stores, along with their IDs, matching the query term. Does not support wildcards. Limit 10 results per query. This API does not consume any credits.
      displayName: 'Search Stores - Lists all stores along with their IDs - Credits:
        ã0'
      queryParameters:
        q:
          type: string
          description: Search term to match against store name or the store domain. Partial match. Case insensitive
          displayName: q
        app_id:
          type: string
          description: Your application id
          displayName: app_id
        app_key:
          type: string
          description: Your application key
          displayName: app_key
      responses:
        200:
          description: Response
  /summary:
    /bulk:
      /lookup:
        post:
          description: This operation returns the summary information for the specified product. This consumes 2 credits per product returned.
          displayName: 'Bulk Product Details - Returns summary information for a product
            - Credits: ãn x 2'
          body:
            multipart/form-data:
              type: object
              properties:
                countryCode:
                  type: string
                  description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
                  displayName: countryCode
                file:
                  type: file
                  description: |-
                    File input format: JsonLines. Each line should be a valid json conforming to one of the below formats<br><pre>{"upc": "upc1"}
                    {"mpn": "mpn1", "brandId":  123}
                    {"sku": "mpn1", "storeId":  123}</pre>
                  displayName: file
                app_id:
                  type: string
                  description: Your application id
                  displayName: app_id
                app_key:
                  type: string
                  description: Your application key
                  displayName: app_key
          responses:
            200:
              description: Response
      /products:
        post:
          description: Returns a collection of products matching a specified query, along with a variety of statistics about the query results. Requires at least one of query, url, upc, mpn, sku, brandId, storeId, or categoryId. This consumes 2 credits per product returned.
          displayName: 'Bulk Search Products - Retrieves a list of products matching
            a variety of query parameters with their summary info - Credits: ãn x
            2'
          body:
            application/x-www-form-urlencoded:
              type: object
              properties:
                countryCode:
                  type: string
                  description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
                  displayName: countryCode
                storeId?:
                  type: array
                  description: 'Limits results to products sold at store with id.
                    Supports multiple values (acts as OR operator) '
                  displayName: storeId
                  items:
                    type: string
                alsoSoldAt?:
                  type: array
                  description: 'Combined with storeId limits results to products sold
                    at both storeIds and alsoSoldAt storeIds. Supports multiple values
                    (acts as OR operator) '
                  displayName: alsoSoldAt
                  items:
                    type: string
                brandId?:
                  type: array
                  description: Limits results to products of brand with id int.  Supports multiple values (acts as OR operator)
                  displayName: brandId
                  items:
                    type: string
                categoryId?:
                  type: array
                  description: Limits results to products of category with this id. Supports multiple values (acts as OR operator)
                  displayName: categoryId
                  items:
                    type: string
                startPrice?:
                  type: string
                  description: Combined with end_price, limits results to products sold by at least one store at a price between start and end
                  displayName: startPrice
                endPrice?:
                  type: string
                  description: Combined with start_price, limits results to products sold by at least one store at a price between start and end
                  displayName: endPrice
                availability?:
                  type: string
                  description: 'Limits results to either in-stock or out-of-stock
                    items. Accepted values: ''IN_STOCK'',''OUT_OF_STOCK'''
                  displayName: availability
                priceHistoryAvailable?:
                  type: string
                  description: 'Limits results to product that have price history
                    available through the products/{:id}/prices endpoint. Accepted
                    values: ''true'',''false'''
                  displayName: priceHistoryAvailable
                priceChange?:
                  type: string
                  description: 'Limits results to products whose prices have been
                    increased or decreased. Accepted Values: PRICE_INCREASED, PRICE_DECREASED,
                    EITHER'
                  displayName: priceChange
                onPromotion?:
                  type: string
                  description: 'Limits results to products which are on Promotion.
                    Accepted values: ''true'',''false'''
                  displayName: onPromotion
                lastRecordedIn?:
                  type: string
                  description: Limits results to products which have price recorded in the last xx days. Accepted Value is a non-negative integer
                  displayName: lastRecordedIn
                storesCount?:
                  type: string
                  description: Limits results to products with at least a certain number of stores
                  displayName: storesCount
                applyFiltersTo?:
                  type: string
                  description: Specify the stores for which the offer level filter apply. Allowed values - storeId (apply filters to only stores in storeId), alsoSoldAt (apply filters to only stores in alsoSoldAt), storeIdOrAlsoSoldAt (apply filters to stores present in both storeId and alsoSoldAt), any (apply filters across all offers)
                  displayName: applyFiltersTo
                selectOffersFrom?:
                  type: string
                  description: Specify the stores for which offers will be returned in the response. Allowed values - storeId (select offers matching filters from storeId), alsoSoldAt (select offers matching filters from alsoSoldAt), storeIdAndAlsoSoldAt (select offers matching filters from stores in both storeId and alsoSoldAt), all (select all offers irrespective of matching or storeId or alsoSoldAt data)
                  displayName: selectOffersFrom
                app_id:
                  type: string
                  description: Your application id
                  displayName: app_id
                app_key:
                  type: string
                  description: Your application key
                  displayName: app_key
          responses:
            200:
              description: Response
    /products:
      /{mpid}:
        uriParameters:
          mpid:
            type: string
            description: The Indix product identifier - should be a 32-digit HEX value retrieved via the Product Search API
            displayName: mpid
        get:
          description: <p>This operation returns the summary information for the specified product. This consumes 2 credits.
          displayName: 'Product Details - Returns summary information for a product
            - Credits: ã2'
          queryParameters:
            countryCode:
              type: string
              description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
              displayName: countryCode
            app_id:
              type: string
              description: Your application id
              displayName: app_id
            app_key:
              type: string
              description: Your application key
              displayName: app_key
          responses:
            200:
              description: Response
      get:
        description: <p>Returns a collection of products matching a specified query, along with a variety of statistics about the query results. Requires at least one of query, url, upc, mpn, sku, brandId, storeId, or categoryId. This consumes 2 credits per product returned.
        displayName: 'Search Products - Retrieves a list of products matching a variety
          of query parameters with their summary info - Credits: ãn x 2'
        queryParameters:
          countryCode:
            type: string
            description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
            displayName: countryCode
          q?:
            type: string
            description: The product search term
            displayName: q
          storeId?:
            type: array
            description: 'Limits results to products sold at store with id. Supports
              multiple values (acts as OR operator) '
            displayName: storeId
            items:
              type: string
          alsoSoldAt?:
            type: array
            description: 'Combined with storeId limits results to products sold at
              both storeIds and alsoSoldAt storeIds. Supports multiple values (acts
              as OR operator) '
            displayName: alsoSoldAt
            items:
              type: string
          brandId?:
            type: array
            description: Limits results to products of brand with id int.  Supports multiple values (acts as OR operator)
            displayName: brandId
            items:
              type: string
          categoryId?:
            type: array
            description: Limits results to products of category with this id. Supports multiple values (acts as OR operator)
            displayName: categoryId
            items:
              type: string
          url?:
            type: string
            description: Search by product URL
            displayName: url
          upc?:
            type: string
            description: Limit results to products with this UPC
            displayName: upc
          mpn?:
            type: string
            description: Limit results to products with this MPN
            displayName: mpn
          sku?:
            type: string
            description: Limit results to products with this SKU
            displayName: sku
          startPrice?:
            type: string
            description: Combined with end_price, limits results to products sold by at least one store at a price between start and end
            displayName: startPrice
          endPrice?:
            type: string
            description: Combined with start_price, limits results to products sold by at least one store at a price between start and end
            displayName: endPrice
          availability?:
            type: string
            description: 'Limits results to either in-stock or out-of-stock items.
              Accepted values: ''IN_STOCK'',''OUT_OF_STOCK'''
            displayName: availability
          priceHistoryAvailable?:
            type: string
            description: 'Limits results to product that have price history available
              through the products/{:id}/prices endpoint. Accepted values: ''true'',''false'''
            displayName: priceHistoryAvailable
          priceChange?:
            type: string
            description: 'Limits results to products whose prices have been increased
              or decreased. Accepted Values: PRICE_INCREASED, PRICE_DECREASED, EITHER'
            displayName: priceChange
          onPromotion?:
            type: string
            description: 'Limits results to products which are on Promotion. Accepted
              values: ''true'',''false'''
            displayName: onPromotion
          lastRecordedIn?:
            type: string
            description: Limits results to products which have price recorded in the last xx days. Accepted Value is a non-negative integer
            displayName: lastRecordedIn
          storesCount?:
            type: string
            description: Limits results to products with at least a certain number of stores
            displayName: storesCount
          applyFiltersTo?:
            type: string
            description: Specify the stores for which the offer level filter apply. Allowed values - storeId (apply filters to only stores in storeId), alsoSoldAt (apply filters to only stores in alsoSoldAt), storeIdOrAlsoSoldAt (apply filters to stores present in both storeId and alsoSoldAt), any (apply filters across all offers)
            displayName: applyFiltersTo
          selectOffersFrom?:
            type: string
            description: Specify the stores for which offers will be returned in the response. Allowed values - storeId (select offers matching filters from storeId), alsoSoldAt (select offers matching filters from alsoSoldAt), storeIdAndAlsoSoldAt (select offers matching filters from stores in both storeId and alsoSoldAt), all (select all offers irrespective of matching or storeId or alsoSoldAt data)
            displayName: selectOffersFrom
          sortBy?:
            type: string
            description: Sort by values - PRICE_LOW_TO_HIGH, PRICE_HIGH_TO_LOW, MOST_RECENT.
            displayName: sortBy
          facetBy?:
            type: array
            description: Facet by values - storeId, brandId, categoryId. Should be a comma separated list of allowed values.
            displayName: facetBy
            items:
              type: string
          pageNumber?:
            type: string
            description: The page number of the result set to return. 10 results per page.
            displayName: pageNumber
          pageSize?:
            type: string
            description: Number of results per page. Allowed values - 10, 20, 50.
            displayName: pageSize
          app_id:
            type: string
            description: Your application id
            displayName: app_id
          app_key:
            type: string
            description: Your application key
            displayName: app_key
        responses:
          200:
            description: Response
  /universal:
    /bulk:
      /ase:
        post:
          description: Used  to  get a set of  exact and close matches for a given set of  query parameters. You must  include <b>productTitle</b> as a parameter. This consumes 25 credits per product returned.
          displayName: 'ASE Universal Bulk - Returns a set of  exact and close matches
            - Credits: ãn x 25'
          body:
            multipart/form-data:
              type: object
              properties:
                countryCode:
                  type: string
                  description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
                  displayName: countryCode
                file:
                  type: file
                  description: |-
                    File input format: JsonLines. Each line should be a valid json conforming to one of the below formats<br><pre>{"productTitle": "Men's Hush  Puppies Circuit Slip  On  MT  Black Leather","brandName": "Hush Puppies","sku": "4784976","mpn": "HM01021-003","upc": "00018467091622"}
                    {"productTitle": "LPS LPS 2 Brown Penetrating Lubricant - 55  gal Drum  - Food  Grade,  Military  Grade - 00255 [PRICE  is  per DRUM]" ,"mpn": "00255","upc": "078827002552"}
                    {"productTitle": "LPS LPS 2 Brown Penetrating Lubricant - 55  gal Drum  - Food  Grade,  Military  Grade - 00255 [PRICE  is  per DRUM]", "upc": "078827002552"}
                    {"productTitle": "LPS LPS 2 Brown Penetrating Lubricant - 55  gal Drum  - Food  Grade,  Military  Grade - 00255 [PRICE  is  per DRUM]"}</pre>
                  displayName: file
                app_id:
                  type: string
                  description: Your application id
                  displayName: app_id
                app_key:
                  type: string
                  description: Your application key
                  displayName: app_key
          responses:
            200:
              description: Response
      /lookup:
        post:
          description: This operation returns the complete information for the specified product across all the stores where it is sold at. This consumes 22 credits per product returned.
          displayName: 'Bulk Product Details - Returns complete information for a
            product - Credits: ãn x 22'
          body:
            multipart/form-data:
              type: object
              properties:
                countryCode:
                  type: string
                  description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
                  displayName: countryCode
                file:
                  type: file
                  description: |-
                    File input format: JsonLines. Each line should be a valid json conforming to one of the below formats<br><pre>{"upc": "upc1"}
                    {"mpn": "mpn1", "brandId":  123}
                    {"sku": "mpn1", "storeId":  123}</pre>
                  displayName: file
                app_id:
                  type: string
                  description: Your application id
                  displayName: app_id
                app_key:
                  type: string
                  description: Your application key
                  displayName: app_key
          responses:
            200:
              description: Response
      /products:
        post:
          description: Returns a collection of products matching a specified query, along with a variety of statistics about the query results. Requires at least one of query, url, upc, mpn, sku, brandId, storeId, or categoryId. This consumes 22 credits per product returned.
          displayName: 'Bulk Search Products - Retrieves a list of products matching
            a variety of query parameters with their offers and catalog info across
            stores - Credits: ãn x 22'
          body:
            application/x-www-form-urlencoded:
              type: object
              properties:
                countryCode:
                  type: string
                  description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
                  displayName: countryCode
                storeId?:
                  type: array
                  description: 'Limits results to products sold at store with id.
                    Supports multiple values (acts as OR operator) '
                  displayName: storeId
                  items:
                    type: string
                alsoSoldAt?:
                  type: array
                  description: 'Combined with storeId limits results to products sold
                    at both storeIds and alsoSoldAt storeIds. Supports multiple values
                    (acts as OR operator) '
                  displayName: alsoSoldAt
                  items:
                    type: string
                brandId?:
                  type: array
                  description: Limits results to products of brand with id int.  Supports multiple values (acts as OR operator)
                  displayName: brandId
                  items:
                    type: string
                categoryId?:
                  type: array
                  description: Limits results to products of category with this id. Supports multiple values (acts as OR operator)
                  displayName: categoryId
                  items:
                    type: string
                startPrice?:
                  type: string
                  description: Combined with end_price, limits results to products sold by at least one store at a price between start and end
                  displayName: startPrice
                endPrice?:
                  type: string
                  description: Combined with start_price, limits results to products sold by at least one store at a price between start and end
                  displayName: endPrice
                availability?:
                  type: string
                  description: 'Limits results to either in-stock or out-of-stock
                    items. Accepted values: ''IN_STOCK'',''OUT_OF_STOCK'''
                  displayName: availability
                priceHistoryAvailable?:
                  type: string
                  description: 'Limits results to product that have price history
                    available through the products/{:id}/prices endpoint. Accepted
                    values: ''true'',''false'''
                  displayName: priceHistoryAvailable
                priceChange?:
                  type: string
                  description: 'Limits results to products whose prices have been
                    increased or decreased. Accepted Values: PRICE_INCREASED, PRICE_DECREASED,
                    EITHER'
                  displayName: priceChange
                onPromotion?:
                  type: string
                  description: 'Limits results to products which are on Promotion.
                    Accepted values: ''true'',''false'''
                  displayName: onPromotion
                lastRecordedIn?:
                  type: string
                  description: Limits results to products which have price recorded in the last xx days. Accepted Value is a non-negative integer
                  displayName: lastRecordedIn
                storesCount?:
                  type: string
                  description: Limits results to products with at least a certain number of stores
                  displayName: storesCount
                applyFiltersTo?:
                  type: string
                  description: Specify the stores for which the offer level filter apply. Allowed values - storeId (apply filters to only stores in storeId), alsoSoldAt (apply filters to only stores in alsoSoldAt), storeIdOrAlsoSoldAt (apply filters to stores present in both storeId and alsoSoldAt), any (apply filters across all offers)
                  displayName: applyFiltersTo
                selectOffersFrom?:
                  type: string
                  description: Specify the stores for which offers will be returned in the response. Allowed values - storeId (select offers matching filters from storeId), alsoSoldAt (select offers matching filters from alsoSoldAt), storeIdAndAlsoSoldAt (select offers matching filters from stores in both storeId and alsoSoldAt), all (select all offers irrespective of matching or storeId or alsoSoldAt data)
                  displayName: selectOffersFrom
                app_id:
                  type: string
                  description: Your application id
                  displayName: app_id
                app_key:
                  type: string
                  description: Your application key
                  displayName: app_key
          responses:
            200:
              description: Response
    /products:
      /{mpid}:
        uriParameters:
          mpid:
            type: string
            description: The Indix product identifier - should be a 32-digit HEX value retrieved via the Product Search API
            displayName: mpid
        get:
          description: <p>This operation returns the complete information for the specified product across all the stores where it is sold at. This consumes 22 credits.
          displayName: 'Product Details - Returns complete information for a product
            - Credits: ã22'
          queryParameters:
            countryCode:
              type: string
              description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
              displayName: countryCode
            pageNumber?:
              type: string
              description: The page number of the result set to return. 50 results per page, plus similar items
              displayName: pageNumber
            app_id:
              type: string
              description: Your application id
              displayName: app_id
            app_key:
              type: string
              description: Your application key
              displayName: app_key
          responses:
            200:
              description: Response
      get:
        description: <p>Returns a collection of products matching a specified query, along with a variety of statistics about the query results. Requires at least one of query, url, upc, mpn, sku, brandId, storeId, or categoryId. This consumes 22 credits per product returned.
        displayName: 'Search Products - Retrieves a list of products matching a variety
          of query parameters with their offers and catalog info across stores - Credits:
          ãn x 22'
        queryParameters:
          countryCode:
            type: string
            description: Limits results to products of the geography with this code. Available values 'US', 'GB', 'IN', 'CA', 'SG' and 'AU'. If the user doesnât pass a value, the default option returns the US countryCode data
            displayName: countryCode
          q?:
            type: string
            description: The product search term
            displayName: q
          storeId?:
            type: array
            description: 'Limits results to products sold at store with id. Supports
              multiple values (acts as OR operator) '
            displayName: storeId
            items:
              type: string
          alsoSoldAt?:
            type: array
            description: 'Combined with storeId limits results to products sold at
              both storeIds and alsoSoldAt storeIds. Supports multiple values (acts
              as OR operator) '
            displayName: alsoSoldAt
            items:
              type: string
          brandId?:
            type: array
            description: Limits results to products of brand with id int. Supports multiple values (acts as OR operator)
            displayName: brandId
            items:
              type: string
          categoryId?:
            type: array
            description: Limits results to products of category with this id. Supports multiple values (acts as OR operator)
            displayName: categoryId
            items:
              type: string
          url?:
            type: string
            description: Search by product URL
            displayName: url
          upc?:
            type: string
            description: Limit results to products with this UPC
            displayName: upc
          mpn?:
            type: string
            description: Limit results to products with this MPN
            displayName: mpn
          sku?:
            type: string
            description: Limit results to products with this SKU
            displayName: sku
          startPrice?:
            type: string
            description: Combined with end_price, limits results to products sold by at least one store at a price between start and end
            displayName: startPrice
          endPrice?:
            type: string
            description: Combined with start_price, limits results to products sold by at least one store at a price between start and end
            displayName: endPrice
          availability?:
            type: string
            description: 'Limits results to either in-stock or out-of-stock items.
              Accepted values: ''IN_STOCK'',''OUT_OF_STOCK'''
            displayName: availability
          priceHistoryAvailable?:
            type: string
            description: 'Limits results to product that have price history available
              through the products/{:id}/prices endpoint. Accepted values: ''true'',''false'''
            displayName: priceHistoryAvailable
          priceChange?:
            type: string
            description: 'Limits results to products whose prices have been increased
              or decreased. Accepted Values: PRICE_INCREASED, PRICE_DECREASED, EITHER'
            displayName: priceChange
          onPromotion?:
            type: string
            description: 'Limits results to products which are on Promotion. Accepted
              values: ''true'',''false'''
            displayName: onPromotion
          lastRecordedIn?:
            type: string
            description: Limits results to products which have price recorded in the last xx days. Accepted Value is a non-negative integer
            displayName: lastRecordedIn
          storesCount?:
            type: string
            description: Limits results to products with at least a certain number of stores
            displayName: storesCount
          applyFiltersTo?:
            type: string
            description: Specify the stores for which the offer level filter apply. Allowed values - storeId (apply filters to only stores in storeId), alsoSoldAt (apply filters to only stores in alsoSoldAt), storeIdOrAlsoSoldAt (apply filters to stores present in both storeId and alsoSoldAt), any (apply filters across all offers)
            displayName: applyFiltersTo
          selectOffersFrom?:
            type: string
            description: Specify the stores for which offers will be returned in the response. Allowed values - storeId (select offers matching filters from storeId), alsoSoldAt (select offers matching filters from alsoSoldAt), storeIdAndAlsoSoldAt (select offers matching filters from stores in both storeId and alsoSoldAt), all (select all offers irrespective of matching or storeId or alsoSoldAt data)
            displayName: selectOffersFrom
          sortBy?:
            type: string
            description: Sort by values - PRICE_LOW_TO_HIGH, PRICE_HIGH_TO_LOW, MOST_RECENT.
            displayName: sortBy
          facetBy?:
            type: array
            description: Facet by values - storeId, brandId, categoryId. Should be a comma separated list of allowed values.
            displayName: facetBy
            items:
              type: string
          pageNumber?:
            type: string
            description: The page number of the result set to return. 10 results per page.
            displayName: pageNumber
          pageSize?:
            type: string
            description: Number of results per page. Allowed values - 10, 20, 50.
            displayName: pageSize
          app_id:
            type: string
            description: Your application id
            displayName: app_id
          app_key:
            type: string
            description: Your application key
            displayName: app_key
        responses:
          200:
            description: Response
