#%RAML 1.0
title: Movie Reviews
version: 2.0.0
baseUri: api.nytimes.com/svc/movies/v2
description: With the Movie Reviews API, you can search New York Times movie reviews by keyword and get lists of NYT Critics' Picks.
mediaType:
- application/json
uses:
  commons: https://raw.githubusercontent.com/apiregistry/commons/master/commons.raml
  extras: https://raw.githubusercontent.com/apiregistry/typesExtras/master/typeExtras.raml
securitySchemes:
  apikey:
    type: Pass Through
types:
  Critic:
    type: object
    properties:
      bio?:
        type: string
      display_name?:
        type: string
      multimedia?:
        type: object
        properties:
          resource?:
            type: object
            properties:
              src?:
                type: string
              width?:
                type: integer
              credit?:
                type: string
              type?:
                type: string
              height?:
                type: integer
      seo_name?:
        type: string
      sort_name?:
        type: string
      status?:
        type: string
  Movie:
    type: object
    properties:
      byline?:
        type: string
      critics_pick?:
        type: integer
      date_updated?:
        type: string
      display_title?:
        type: string
      headline?:
        type: string
      link?:
        type: object
        properties:
          suggested_link_text?:
            type: string
          type?:
            type: string
          url?:
            type: string
      mpaa_rating?:
        type: string
      multimedia?:
        type: object
        properties:
          resource?:
            type: object
            properties:
              src?:
                type: string
              width?:
                type: integer
              type?:
                type: string
              height?:
                type: integer
      opening_date?:
        type: string
      publication_date?:
        type: string
      summary_short?:
        type: string
/critics:
  /{resource-type}.json:
    uriParameters:
      resource-type:
        type: string
        description: |
          all | full-time | part-time | [reviewer-name]

          Specify all to get all Times reviewers, or specify full-time or part-time to get that subset. Specify a reviewer's name to get details about a particular reviewer.
        displayName: resource-type
    get:
      responses:
        200:
          description: An array of Movie Critics
          body:
            application/json:
              type: object
              properties:
                copyright?:
                  type: string
                results?:
                  type: array
                  items:
                    type: Critic
                num_results?:
                  type: integer
                status?:
                  type: string
/reviews:
  /search.json:
    get:
      queryParameters:
        query?:
          type: string
          description: "Search keywords; matches movie title and indexed terms\n\n\
            To limit your search to exact matches only, surround your search string\
            \ with single quotation marks (e.g., query='28+days+later'). Otherwise,\
            \ responses will include partial matches (\"head words\") as well as exact\
            \ matches (e.g., president will match president, presidents and presidential).\n\
            \  \n  If you specify multiple terms without quotation marks, they will\
            \ be combined in an OR search.\n  \n  If you omit the query parameter,\
            \ your request will be equivalent to a reviews and NYT Critics' Picks\
            \ request.\n"
          displayName: query
        critics-pick?:
          type: string
          description: |
            Set this parameter to Y to limit the results to NYT Critics' Picks. To get only those movies that have not been highlighted by Times critics, specify critics-pick=N. (To get all reviews regardless of critics-pick status, simply omit this parameter.)
          displayName: critics-pick
          enum:
          - Y
          - N
        reviewer?:
          type: string
          description: |
            Include this parameter to limit your results to reviews by a specific critic. Reviewer names should be formatted like this: Manohla Dargis.
          displayName: reviewer
        publication-date?:
          type: string
          description: |
            Single date: YYYY-MM-DD

            Start and end date: YYYY-MM-DD;YYYY-MM-DD

            The publication-date is the date the review was first published in The Times.
          displayName: publication-date
        opening-date?:
          type: string
          description: |
            Single date: YYYY-MM-DD

            Start and end date: YYYY-MM-DD;YYYY-MM-DD

            The opening-date is the date the movie's opening date in the New York region.
          displayName: opening-date
        offset?:
          type: integer
          description: Positive integer, multiple of 20
          displayName: offset
          default: 20
        order?:
          type: string
          description: |
            Sets the sort order of the results.

            Results ordered by-title are in ascending alphabetical order. Results ordered by one of the date parameters are in reverse chronological order.

            If you do not specify a sort order, the results will be ordered by publication-date.
          displayName: order
      responses:
        200:
          description: An array of Movies
          body:
            application/json:
              type: object
              properties:
                copyright?:
                  type: string
                results?:
                  type: array
                  items:
                    type: Movie
                num_results?:
                  type: integer
                status?:
                  type: string
  /{resource-type}.json:
    uriParameters:
      resource-type:
        type: string
        description: |+
          Specify all to retrieve all reviews, including NYT Critics' Picks.

          Specify picks to get NYT Critics' Picks currently in theaters.

        displayName: resource-type
        enum:
        - all
        - picks
    get:
      queryParameters:
        offset?:
          type: integer
          description: Positive integer, multiple of 20
          displayName: offset
          default: 20
        order?:
          type: string
          description: |
            Sets the sort order of the results.

            Results ordered by-title are in ascending alphabetical order. Results ordered by one of the date parameters are in reverse chronological order.

            If you do not specify a sort order, the results will be ordered by publication-date.
          displayName: order
          default: by-publication-date
          enum:
          - by-title
          - by-publication-date
          - by-opening-date
      responses:
        200:
          description: An array of Movies
          body:
            application/json:
              type: object
              properties:
                copyright?:
                  type: string
                results?:
                  type: array
                  items:
                    type: Movie
                num_results?:
                  type: integer
                status?:
                  type: string
