#%RAML 1.0
title: OMDb
version: '1'
baseUri: www.omdbapi.com/
description: The Open Movie Database. The OMDb API is a free web service to obtain movie information, all content and images on the site are contributed and maintained by our users.
mediaType:
- application/json
- application/xml
uses:
  commons: https://raw.githubusercontent.com/apiregistry/commons/master/commons.raml
  extras: https://raw.githubusercontent.com/apiregistry/typesExtras/master/typeExtras.raml
types:
  combinedResult:
    type: object
    properties:
      Actors?:
        type: string
      Awards?:
        type: string
      BoxOffice?:
        type: string
      Country?:
        type: string
      DVD?:
        type: string
      Director?:
        type: string
      Genre?:
        type: string
      Language?:
        type: string
      Metascore?:
        type: string
      Plot?:
        type: string
      Poster?:
        type: string
      Production?:
        type: string
      Rated?:
        type: string
      Released?:
        type: string
      Response:
        type: string
      Runtime?:
        type: string
      Search?:
        type: array
        items:
          type: object
          properties:
            Type?:
              type: string
            Year?:
              type: string
            imdbID?:
              type: string
            Poster?:
              type: string
            Title?:
              type: string
      Title?:
        type: string
      Type?:
        type: string
      Website?:
        type: string
      Writer?:
        type: string
      Year?:
        type: string
      imdbID?:
        type: string
      imdbRating?:
        type: string
      imdbVotes?:
        type: string
      tomatoConsensus?:
        type: string
      tomatoFresh?:
        type: string
      tomatoImage?:
        type: string
      tomatoMeter?:
        type: string
      tomatoRating?:
        type: string
      tomatoReviews?:
        type: string
      tomatoRotten?:
        type: string
      tomatoURL?:
        type: string
      tomatoUserMeter?:
        type: string
      tomatoUserRating?:
        type: string
      tomatoUserReviews?:
        type: string
      totalResults?:
        type: string
      totalSeasons?:
        type: string
/:
  get:
    description: Find a movie, series or episode from the OMDb by title, IMDb-id or by free-text search
    displayName: OMDb Search
    queryParameters:
      t?:
        type: string
        description: Movie title to search for. One of t, i or s is required.
        displayName: t
      i?:
        type: string
        description: A valid IMDb ID (e.g. tt1285016). One of t, i or s is required.
        displayName: i
      s?:
        type: string
        description: Movie title to search for. One of t, i or s is required.
        displayName: s
      y?:
        type: integer
        description: Year of release.
        displayName: y
      type?:
        type: string
        description: Type of result to return.
        displayName: type
        enum:
        - movie
        - series
        - episode
      plot?:
        type: string
        description: Return short or full plot.
        displayName: plot
        default: short
        enum:
        - short
        - full
      tomatoes?:
        type: boolean
        description: Include Rotten Tomatoes ratings.
        displayName: tomatoes
        default: false
      r:
        type: string
        description: The data type to return.
        displayName: r
        default: json
        enum:
        - json
        - xml
      v?:
        type: integer
        description: API version (reserved for future use).
        displayName: v
        default: 1
      page?:
        type: integer
        description: Page number to return.
        displayName: page
        default: 1
        format: int32
      callback?:
        type: string
        description: JSONP callback name.
        displayName: callback
    responses:
      200:
        description: Default response
        body:
          application/json:
            type: combinedResult
          application/xml:
            type: combinedResult
