#%RAML 1.0
title: Oxford Dictionaries
version: 1.3.0
baseUri: od-api.oxforddictionaries.com/api/v1
mediaType:
- application/json
uses:
  commons: https://raw.githubusercontent.com/apiregistry/commons/master/commons.raml
  extras: https://raw.githubusercontent.com/apiregistry/typesExtras/master/typeExtras.raml
types:
  VariantForms:
    type: array
    description: Various words that are used interchangeably depending on the context, e.g 'aluminium' and 'aluminum'
    items:
      type: object
      properties:
        regions?:
          type: arrayofstrings
          description: A particular area in which the variant form occurs, e.g. 'Great Britain'
        text?:
          type: string
  arrayofstrings:
    type: array
    items:
      type: string
  CrossReference:
    type: object
    properties:
      id?:
        type: string
        description: The word id of cooccurrence
      sense_id?:
        type: string
        description: The id of the sense that co-occurs
      text?:
        type: string
        description: The word of cooccurrence
      type?:
        type: string
        description: The type of relation between the two words. Possible values are 'close match', 'related', 'see also', 'variant spelling', and 'abbreviation' in case of crossreferences, or 'pre', 'post' in case of collocates.
    description: cross references of a sense
  Entry:
    type: object
    properties:
      editorialNotes?:
        type: arrayofstrings
        description: Editorial information intended to help a human reader understand the sense
      etymologies?:
        type: arrayofstrings
        description: The origin of the word and the way in which its meaning has changed throughout history
      grammaticalFeatures?:
        type: array
        description: The different forms are correlated with meanings or functions which we text as 'features'
        items:
          type: object
          properties:
            text?:
              type: string
            type?:
              type: string
      homographNumber?:
        type: string
        description: Identifies the homograph grouping. The last two digits identify different entries of the same homograph. The first one/two digits identify the homograph number.
      pronunciations?:
        type: array
        description: A grouping of pronunciation information
        items:
          type: Pronunciation
      senses?:
        type: array
        description: Complete list of senses
        items:
          type: Sense
      variantForms?:
        type: VariantForms
        description: Various words that are used interchangeably depending on the context, e.g 'a' and 'an'
  Filters:
    type: object
    properties:
      metadata?:
        type: object
        description: Additional Information provided by OUP
      results?:
        type: object
        properties:
          entries?:
            type: arrayofstrings
            description: A list of filters available for Dictionary Entry endpoint
          translations?:
            type: arrayofstrings
            description: A list of filters available for Translation endpoint
          inflections?:
            type: arrayofstrings
            description: A list of filters available for Lemmatron endpoint
        description: A mapping of filters available per endpoints.
    description: Schema for the Filters endpoint.
  Inflection:
    type: object
    properties:
      id?:
        type: string
        description: Inflected word ID
      text?:
        type: string
    description: A grouping of the modifications of a word to express different grammatical categories
  Labels:
    type: object
    properties:
      metadata?:
        type: object
        description: Additional Information provided by OUP
      results?:
        type: ^_a-zA-Z_+$
        description: Mapping of labels available.
    description: Schema for lexicalcategories, registers utility endpoints.
  Languages:
    type: object
    properties:
      metadata?:
        type: object
        description: Additional Information provided by OUP
      results?:
        type: array
        description: A list of languages available.
        items:
          type: object
          properties:
            targetLanguage?:
              type: object
              properties:
                language?:
                  type: string
                  description: Language label.
                id?:
                  type: string
                  description: IANA language code
            source?:
              type: string
              description: Name of source dictionary.
            region?:
              type: string
              description: Name of region.
            type?:
              type: string
              description: whether monolingual or bilingual.
              enum:
              - monolingual
              - bilingual
            sourceLanguage?:
              type: object
              properties:
                language?:
                  type: string
                  description: Language label.
                id?:
                  type: string
                  description: IANA language code
    description: Schema for the languages endpoint.
  Lemmatron:
    type: object
    properties:
      metadata?:
        type: object
        description: Additional Information provided by OUP
      results?:
        type: array
        description: A list of inflections matching given word
        items:
          type: object
          properties:
            lexicalEntries?:
              type: array
              description: A grouping of various senses in a specific language, and a lexical category that relates to a word
              items:
                type: lexicalEntry
            language?:
              type: string
              description: IANA language code
            id?:
              type: string
              description: The identifier of a word
            word?:
              type: string
              description: A given written or spoken realisation of a an entry, lowercased.
          description: Description of an inflection word
    description: Schema for the inflections endpoint.
  Pronunciation:
    type: object
    properties:
      audioFile?:
        type: string
        description: The URL of the sound file
      phoneticsNotation?:
        type: string
        description: The alphabetic system used to display the phonetic spelling
      phoneticsSpelling?:
        type: string
        description: Phonetic spelling is the representation of vocal sounds which express pronunciations of words. It is a system of spelling in which each letter represents invariably the same spoken sound
      regions?:
        type: arrayofstrings
        description: A particular area in which the pronunciation occurs, e.g. 'Great Britain'
    description: A grouping of pronunciation information
  Regions:
    type: object
    properties:
      metadata?:
        type: object
        description: Additional Information provided by OUP
      results?:
        type: array
        description: The list of labels for an object. Every object is region name.
        items:
          type: object
          properties:
            text?:
              type: string
    description: Schema for regions endpoint.
  RetrieveEntry:
    type: object
    properties:
      metadata?:
        type: object
        description: Additional Information provided by OUP
      results?:
        type: array
        description: A list of entries and all the data related to them
        items:
          type: object
          properties:
            lexicalEntries?:
              type: array
              description: A grouping of various senses in a specific language, and a lexical category that relates to a word
              items:
                type: lexicalEntry
            language?:
              type: string
              description: IANA language code
            id?:
              type: string
              description: The identifier of a word
            word?:
              type: string
              description: A given written or spoken realisation of a an entry, lowercased.
            pronunciations?:
              type: array
              description: A grouping of pronunciation information
              items:
                type: Pronunciation
          description: Description of a word
    description: Schema for the 'entries' endpoints
  Sense:
    type: object
    properties:
      closeMatches?:
        type: arrayofstrings
        description: A reference to another word that is closely related
      crossReferences?:
        type: array
        description: A reference to another word that is closely related, might provide additional information about the subject, has a variant spelling or is an abbreviated form of it.
        items:
          type: CrossReference
      definitions?:
        type: arrayofstrings
        description: A list of statements of the exact meaning of a word
      domains?:
        type: arrayofstrings
        description: A subject, discipline, or branch of knowledge particular to the Sense
      examples?:
        type: array
        description: A list of written or spoken rendering of examples of use of a word or text
        items:
          type: object
          properties:
            text?:
              type: string
      grammaticalNotes?:
        type: arrayofstrings
        description: Show transitivity statements or usage notes.
      id?:
        type: string
        description: The id of the sense that is required for the delete procedure
      markers?:
        type: arrayofstrings
        description: Editorial information intended to help a reader understand the Sense
      parentSense?:
        type: string
        description: This sense has a super sense.
      pronunciations?:
        type: array
        description: A grouping of pronunciation information
        items:
          type: Pronunciation
      regions?:
        type: arrayofstrings
        description: A particular area in which the Sense occurs, e.g. 'Great Britain'
      registers?:
        type: arrayofstrings
        description: A level of language usage, typically with respect to formality. e.g. 'offensive', 'informal'
      relatedTo?:
        type: arrayofstrings
        description: A reference to a related word
      seeAlso?:
        type: arrayofstrings
        description: A reference to a resource that might provide additional information about the subject
      variantForms?:
        type: VariantForms
        description: Various words that are used interchangeably depending on the context, e.g 'duck' and 'duck boat'
    description: A lexical sense represents the lexical meaning of a lexical entry when interpreted as referring to the corresponding ontology element
  Sentences:
    type: object
    properties:
      metadata?:
        type: object
        description: Additional Information provided by OUP
      results?:
        type: array
        description: A list of found words
        items:
          type: object
          properties:
            lexicalEntries?:
              type: array
              description: Grammatical features, Lexical category and Sentences.
              items:
                type: object
                properties:
                  grammaticalFeatures?:
                    type: string
                  sentences?:
                    type: array
                  lexicalCategory?:
                    type: string
                  language?:
                    type: string
                description: List of found sentences.
            language?:
              type: string
              description: IANA code.
            id?:
              type: string
              description: The identifier of a word
          description: Description of found word
    description: Schema for sentences endpoint.
  Wordlist:
    type: object
    properties:
      metadata?:
        type: object
        description: Additional Information provided by OUP
      results?:
        type: array
        description: A list of found words
        items:
          type: object
          properties:
            id?:
              type: string
              description: The identifier of a word
            word?:
              type: string
              description: A given written or spoken realisation of a an entry, lowercased.
          description: Description of found word
    description: Schema for wordlist endpoint.
  ^_a-zA-Z_+$:
    type: object
    properties:
      en?:
        type: string
        description: Label in English
    description: The list of labels for an object. Every object can be a lexical category, or a register, or a domain.
  lexicalEntry:
    type: object
    properties:
      entries?:
        type: array
        items:
          type: Entry
      grammaticalFeatures?:
        type: array
        description: The different forms are correlated with meanings or functions which we text as 'features'
        items:
          type: object
          properties:
            text?:
              type: string
            type?:
              type: string
      grammaticalNotes?:
        type: arrayofstrings
        description: Show transitivity statements or usage notes.
      inflectionOf?:
        type: array
        description: The canonical form of words for which the entry is an inflection
        items:
          type: Inflection
      inflections?:
        type: array
        description: The modification of a word to express different grammatical categories
        items:
          type: Inflection
      language?:
        type: string
        description: IANA language code
      lexicalCategory?:
        type: string
        description: A linguistic category of words (or more precisely lexical items), generally defined by the syntactic or morphological behaviour of the lexical item in question, such as noun or verb
      pronunciations?:
        type: array
        description: A grouping of pronunciation information
        items:
          type: Pronunciation
      text?:
        type: string
        description: A given written or spoken realisation of a an entry.
      variantForms?:
        type: VariantForms
        description: Various words that are used interchangeably depending on the context, e.g 'a' and 'an'
    description: Description of an entry for a particular part of speech
/domains:
  /{source_language}:
    uriParameters:
      source_language:
        type: string
        description: IANA language code. Source Language.
        displayName: source_language
        enum:
        - en
        - es
        - lv
        - nso
        - ro
        - zu
    /{target_language}:
      uriParameters:
        target_language:
          type: string
          description: IANA language code. Target Language.
          displayName: target_language
          enum:
          - es
          - en
          - lv
          - nso
          - ro
          - zu
      get:
        description: |
          Returns a list of the available domains for a given bilingual language dataset.
        displayName: Lists available domains in a given bilingual language dataset.
        headers:
          app_id:
            type: string
            description: App ID Authentication Parameter
            displayName: app_id
            default: 5037d509
          app_key:
            type: string
            description: App Key Authentication Parameter
            displayName: app_key
            default: 4dc1aebaa63721f0f8e79a55e2514bc7
        responses:
          200:
            description: Successful response.
            body:
              application/json:
                type: Labels
                displayName: DomainsResults
          400:
            description: source_language and target_language are same.
          404:
            description: Unknown source_language and/or target_language.
    get:
      description: |
        Returns a list of the available domains for a given monolingual language dataset.
      displayName: Lists available domains in a given monolingual language dataset.
      headers:
        app_id:
          type: string
          description: App ID Authentication Parameter
          displayName: app_id
          default: 5037d509
        app_key:
          type: string
          description: App Key Authentication Parameter
          displayName: app_key
          default: 4dc1aebaa63721f0f8e79a55e2514bc7
      responses:
        200:
          description: Successful response.
          body:
            application/json:
              type: Labels
              displayName: DomainsResults
        404:
          description: Unknown source_language.
/entries:
  /{source_language}:
    uriParameters:
      source_language:
        type: string
        description: IANA language code.
        displayName: source_language
        enum:
        - en
        - es
    /{word_id}:
      uriParameters:
        word_id:
          type: string
          description: An Entry identifier. Case-sensitive.
          displayName: word_id
          default: ace
      /sentences:
        get:
          description: |2

            Retrieve list of sentences and list of senses (English language only).
              <div id="sentences"></div>
          displayName: Retrieve corpus sentences for a given word.
          headers:
            app_id:
              type: string
              description: App ID Authentication Parameter
              displayName: app_id
              default: 5037d509
            app_key:
              type: string
              description: App Key Authentication Parameter
              displayName: app_key
              default: 4dc1aebaa63721f0f8e79a55e2514bc7
          responses:
            200:
              description: Successful response.
              body:
                application/json:
                  type: Sentences
                  displayName: SentencesResults
            404:
              description: |
                No entry is found matching supplied id and source_language
            500:
              description: |
                Internal Error. An error occurred while processing the data.
  /{source_lang}:
    uriParameters:
      source_lang:
        type: string
        description: IANA language code
        displayName: source_lang
        enum:
        - en
        - es
        - lv
        - hi
    /{word_id}:
      uriParameters:
        word_id:
          type: string
          description: An Entry identifier. Case-sensitive.
          displayName: word_id
          default: ace
      /antonyms:
        get:
          description: "\nRetrieve available antonyms for a given word and language.\
            \ \n\n  <div id=\"antonyms\"></div>\n"
          displayName: Retrieve antonyms for a given word.
          headers:
            app_id:
              type: string
              description: App ID Authentication Parameter
              displayName: app_id
              default: 5037d509
            app_key:
              type: string
              description: App Key Authentication Parameter
              displayName: app_key
              default: 4dc1aebaa63721f0f8e79a55e2514bc7
          responses:
            200:
              description: Successful response.
              body:
                application/json:
                  type: RetrieveEntry
                  displayName: RetrieveEntryResults
            404:
              description: |
                No entry is found matching supplied id and source_lang or filters are not recognized
            500:
              description: |
                Internal Error. An error occurred while processing the data.
      /definitions:
        get:
          description: "\nFind available [dictionary entries](/glossary?tag=#entry&expand)\
            \ for given word and language. Filter results by categories. \n\n  <div\
            \ id=\"dictionary_entries_filters_definitions\"></div>\n"
          displayName: Retrieve only definitions in entry search.
          headers:
            app_id:
              type: string
              description: App ID Authentication Parameter
              displayName: app_id
              default: 5037d509
            app_key:
              type: string
              description: App Key Authentication Parameter
              displayName: app_key
              default: 4dc1aebaa63721f0f8e79a55e2514bc7
          responses:
            200:
              description: Successful response.
              body:
                application/json:
                  type: RetrieveEntry
                  displayName: RetrieveEntryResults
            404:
              description: "no entry is found matching supplied source_lang and id\n\
                and/or that entry has no senses with translations in the target language.\
                \ \n"
            500:
              description: |
                Internal Error. An error occourred while processing the data.
      /examples:
        get:
          description: "\nFind available [dictionary entries](/glossary?tag=#entry&expand)\
            \ for given word and language. Filter results by categories. \n\n  <div\
            \ id=\"dictionary_entries_filters_examples\"></div>\n"
          displayName: Retrieve only example sentences in entry search.
          headers:
            app_id:
              type: string
              description: App ID Authentication Parameter
              displayName: app_id
              default: 5037d509
            app_key:
              type: string
              description: App Key Authentication Parameter
              displayName: app_key
              default: 4dc1aebaa63721f0f8e79a55e2514bc7
          responses:
            200:
              description: Successful response.
              body:
                application/json:
                  type: RetrieveEntry
                  displayName: RetrieveEntryResults
            404:
              description: "no entry is found matching supplied source_lang and id\n\
                and/or that entry has no senses with translations in the target language.\
                \ \n"
            500:
              description: |
                Internal Error. An error occourred while processing the data.
      /pronunciations:
        get:
          description: "\nFind available [dictionary entries](/glossary?tag=#entry&expand)\
            \ for given word and language. Filter results by categories. \n\n  <div\
            \ id=\"dictionary_entries_filters_pronunciations\"></div>\n"
          displayName: Retrieve only pronunciations in entry search.
          headers:
            app_id:
              type: string
              description: App ID Authentication Parameter
              displayName: app_id
              default: 5037d509
            app_key:
              type: string
              description: App Key Authentication Parameter
              displayName: app_key
              default: 4dc1aebaa63721f0f8e79a55e2514bc7
          responses:
            200:
              description: Successful response.
              body:
                application/json:
                  type: RetrieveEntry
                  displayName: RetrieveEntryResults
            404:
              description: "no entry is found matching supplied source_lang and id\n\
                and/or that entry has no senses with translations in the target language.\
                \ \n"
            500:
              description: |
                Internal Error. An error occourred while processing the data.
      /regions={region}:
        uriParameters:
          region:
            type: string
            description: Region filter parameter. gb = Great Britain English. us = United States English. Default is gb.
            displayName: region
            enum:
            - gb
            - us
        get:
          description: "\nRetrieve available [dictionary entries](/glossary?tag=#entry&expand)\
            \ for given word and language. \n\n  <div id=\"dictionary_entries\"></div>\n"
          displayName: Specify GB or US dictionary for English entry search.
          headers:
            app_id:
              type: string
              description: App ID Authentication Parameter
              displayName: app_id
              default: 5037d509
            app_key:
              type: string
              description: App Key Authentication Parameter
              displayName: app_key
              default: 4dc1aebaa63721f0f8e79a55e2514bc7
          responses:
            200:
              description: Successful response.
              body:
                application/json:
                  type: RetrieveEntry
                  displayName: RetrieveEntryResults
            404:
              description: "no entry is found matching supplied source_lang and id\n\
                and/or that entry has no senses with translations in the target language.\
                \ \n"
            500:
              description: |
                Internal Error. An error occourred while processing the data.
      /synonyms:
        get:
          description: "\nRetrieve available synonyms for a given word and language.\
            \ \n\n  <div id=\"synonyms\"></div>\n"
          displayName: Retrieve synonyms for a given word.
          headers:
            app_id:
              type: string
              description: App ID Authentication Parameter
              displayName: app_id
              default: 5037d509
            app_key:
              type: string
              description: App Key Authentication Parameter
              displayName: app_key
              default: 4dc1aebaa63721f0f8e79a55e2514bc7
          responses:
            200:
              description: Successful response.
              body:
                application/json:
                  type: RetrieveEntry
                  displayName: RetrieveEntryResults
            404:
              description: |
                No entry is found matching supplied id and source_lang or filters are not recognized
            500:
              description: |
                Internal Error. An error occurred while processing the data.
      /synonyms;antonyms:
        get:
          description: "\nRetrieve available synonyms and antonyms for a given word\
            \ and language. \n\n  <div id=\"synonyms_and_antonyms\"></div>\n"
          displayName: Retrieve synonyms and antonyms for a given word.
          headers:
            app_id:
              type: string
              description: App ID Authentication Parameter
              displayName: app_id
              default: 5037d509
            app_key:
              type: string
              description: App Key Authentication Parameter
              displayName: app_key
              default: 4dc1aebaa63721f0f8e79a55e2514bc7
          responses:
            200:
              description: Successful response.
              body:
                application/json:
                  type: RetrieveEntry
                  displayName: RetrieveEntryResults
            404:
              description: |
                No entry is found matching supplied id and source_lang or filters are not recognized
            500:
              description: |
                Internal Error. An error occurred while processing the data.
      /translations={target_lang}:
        uriParameters:
          target_lang:
            type: string
            description: IANA language code
            displayName: target_lang
            enum:
            - es
            - en
            - lv
            - nso
            - ro
            - zu
            - ms
            - id
            - tn
        get:
          description: "Returns target language translations for a given word ID and\
            \ source language. \nIn the event that a word in the dataset does not\
            \ have a direct translation, the response will be a definition in the\
            \ target language.\n\n  <div id=\"translation\"></div>\n"
          displayName: Find translation for a given word.
          headers:
            app_id:
              type: string
              description: App ID Authentication Parameter
              displayName: app_id
              default: 5037d509
            app_key:
              type: string
              description: App Key Authentication Parameter
              displayName: app_key
              default: 4dc1aebaa63721f0f8e79a55e2514bc7
          responses:
            200:
              description: Successful response. In case word doesn't have a direct translation a response would be definitions.
              body:
                application/json:
                  type: RetrieveEntry
                  displayName: TranslationsResults
            400:
              description: any of target languages is unknown
            404:
              description: "no entry is found matching supplied source_lang and id\n\
                and/or that entry has no senses with translations in the target language(s).\
                \ \n"
            500:
              description: |
                Internal Error. An error occourred while processing the data.
      /{filters}:
        uriParameters:
          filters:
            type: array
            description: Separate filtering conditions using a semicolon. Conditions take values grammaticalFeatures and/or lexicalCategory and are case-sensitive. To list multiple values in single condition divide them with comma.
            displayName: filters
            default: '[grammaticalFeatures=singular,past;lexicalCategory=noun]'
            items:
              type: string
              pattern: (lexicalCategory|grammaticalFeatures)=.+
        get:
          description: "\nFind available [dictionary entries](/glossary?tag=#entry&expand)\
            \ for given word and language. Filter results by categories. \n\n  <div\
            \ id=\"dictionary_entries_filters\"></div>\n"
          displayName: Apply filters to entry search.
          headers:
            app_id:
              type: string
              description: App ID Authentication Parameter
              displayName: app_id
              default: 5037d509
            app_key:
              type: string
              description: App Key Authentication Parameter
              displayName: app_key
              default: 4dc1aebaa63721f0f8e79a55e2514bc7
          responses:
            200:
              description: Successful response.
              body:
                application/json:
                  type: RetrieveEntry
                  displayName: RetrieveEntryResults
            404:
              description: "no entry is found matching supplied source_lang and id\n\
                and/or that entry has no senses with translations in the target language.\
                \ \n"
            500:
              description: |
                Internal Error. An error occourred while processing the data.
      get:
        description: "\nRetrieve available [dictionary entries](/glossary?tag=#entry&expand)\
          \ for a given word and language. \n\n  <div id=\"dictionary_entries\"></div>\n"
        displayName: Retrieve dictionary entries for a given word.
        headers:
          app_id:
            type: string
            description: App ID Authentication Parameter
            displayName: app_id
            default: 5037d509
          app_key:
            type: string
            description: App Key Authentication Parameter
            displayName: app_key
            default: 4dc1aebaa63721f0f8e79a55e2514bc7
        responses:
          200:
            description: Successful response.
            body:
              application/json:
                type: RetrieveEntry
                displayName: RetrieveEntryResults
          404:
            description: |
              No entry is found matching supplied id and source_lang or filters are not recognized
          500:
            description: |
              Internal Error. An error occurred while processing the data.
/filters:
  /{endpoint}:
    uriParameters:
      endpoint:
        type: string
        description: Name of the endpoint.
        displayName: endpoint
        enum:
        - entries
        - inflections
        - translations
    get:
      description: |
        Returns a list of all the valid filters for a given endpoint to construct API calls.
      displayName: Lists available filters for specific endpoint.
      headers:
        app_id:
          type: string
          description: App ID Authentication Parameter
          displayName: app_id
          default: 5037d509
        app_key:
          type: string
          description: App Key Authentication Parameter
          displayName: app_key
          default: 4dc1aebaa63721f0f8e79a55e2514bc7
      responses:
        200:
          description: Successful response.
          body:
            application/json:
              type: Filters
              displayName: FiltersResults
        404:
          description: Unknown endpoint.
        500:
          description: Internal Error. An error occourred while processing the data.
  get:
    description: |
      Returns a list of all the valid filters to construct API calls.
    displayName: Lists available filters.
    headers:
      app_id:
        type: string
        description: App ID Authentication Parameter
        displayName: app_id
        default: 5037d509
      app_key:
        type: string
        description: App Key Authentication Parameter
        displayName: app_key
        default: 4dc1aebaa63721f0f8e79a55e2514bc7
    responses:
      200:
        description: Successful response.
        body:
          application/json:
            type: Filters
            displayName: FiltersResults
      500:
        description: Internal Error. An error occourred while processing the data.
/inflections:
  /{source_lang}:
    uriParameters:
      source_lang:
        type: string
        description: IANA language code
        displayName: source_lang
        enum:
        - en
        - es
        - lv
        - hi
    /{word_id}:
      uriParameters:
        word_id:
          type: string
          description: An inflected wordform. Case-sensitive.
          displayName: word_id
          default: changed
      /{filters}:
        uriParameters:
          filters:
            type: array
            description: Separate filtering conditions using a semicolon. Conditions take values grammaticalFeatures and/or lexicalCategory and are case-sensitive. To list multiple values in single condition divide them with comma.
            displayName: filters
            default: '[grammaticalFeatures=singular,past;lexicalCategory=noun]'
            items:
              type: string
              pattern: (lexicalCategory|grammaticalFeatures)=.+
        get:
          description: "\nRetrieve available [lemmas](/glossary?tag=#lemma&expand)\
            \ for a given [inflected](/glossary?tag=#inflection&expand) wordform.\
            \ Filter results by categories.  \n\n  <div id=\"lemmatron_filters\"></div>\n"
          displayName: Apply filters to Lemmatron response
          headers:
            app_id:
              type: string
              description: App ID Authentication Parameter
              displayName: app_id
              default: 5037d509
            app_key:
              type: string
              description: App Key Authentication Parameter
              displayName: app_key
              default: 4dc1aebaa63721f0f8e79a55e2514bc7
          responses:
            200:
              description: Successful response.
              body:
                application/json:
                  type: Lemmatron
                  displayName: InflectionsResults
            500:
              description: |
                Internal Error. An error occourred while processing the data.
      get:
        description: "\nRetrieve available [lemmas](/glossary?tag=#lemma&expand) for\
          \ a given [inflected](/glossary?tag=#inflection&expand) wordform. \n\n \
          \ <div id=\"lemmatron\"></div>\n"
        displayName: Retrieve lemmas for a given inflected wordform.
        headers:
          app_id:
            type: string
            description: App ID Authentication Parameter
            displayName: app_id
            default: 5037d509
          app_key:
            type: string
            description: App Key Authentication Parameter
            displayName: app_key
            default: 4dc1aebaa63721f0f8e79a55e2514bc7
        responses:
          200:
            description: Successful response.
            body:
              application/json:
                type: Lemmatron
                displayName: InflectionsResults
          500:
            description: |
              Internal Error. An error occourred while processing the data.
/languages:
  get:
    description: |
      Returns a list of monolingual and bilingual language datasets available in the API
    displayName: Lists available monolingual and bilingual language datasets in the API.
    queryParameters:
      sourceLanguage?:
        type: string
        description: IANA language code. If provided output will be filtered by sourceLanguage.
        displayName: sourceLanguage
        enum:
        - en
        - es
        - lv
        - nso
        - ro
        - zu
        - ms
        - id
        - tn
        - ur
      targetLanguage?:
        type: string
        description: IANA language code. If provided output will be filtered by sourceLanguage.
        displayName: targetLanguage
        enum:
        - es
        - en
        - lv
        - nso
        - ro
        - zu
        - ms
        - id
        - tn
    headers:
      app_id:
        type: string
        description: App ID Authentication Parameter
        displayName: app_id
        default: 5037d509
      app_key:
        type: string
        description: App Key Authentication Parameter
        displayName: app_key
        default: 4dc1aebaa63721f0f8e79a55e2514bc7
    responses:
      200:
        description: Successful response.
        body:
          application/json:
            type: Languages
            displayName: LanguagesResults
      404:
        description: Unknown sourceLanguage and/or targetLanguage.
      500:
        description: Internal Error. An error occourred while processing the data.
/lexicalcategories:
  /{language}:
    uriParameters:
      language:
        type: string
        description: IANA language code
        displayName: language
        enum:
        - en
        - es
        - lv
        - nso
        - ro
        - zu
    get:
      description: |
        Returns a list of available lexical categories for a given language dataset.
      displayName: Lists available lexical categories in a given language dataset.
      headers:
        app_id:
          type: string
          description: App ID Authentication Parameter
          displayName: app_id
          default: 5037d509
        app_key:
          type: string
          description: App Key Authentication Parameter
          displayName: app_key
          default: 4dc1aebaa63721f0f8e79a55e2514bc7
      responses:
        200:
          description: Successful response.
          body:
            application/json:
              type: Labels
              displayName: LexicalCategoriesResults
        404:
          description: Unknown language.
        500:
          description: Internal Error. An error occourred while processing the data.
/regions:
  /{source_language}:
    uriParameters:
      source_language:
        type: string
        description: IANA language code
        displayName: source_language
        enum:
        - en
    get:
      description: |
        Returns a list of the available regions for a given monolingual language dataset.
      displayName: Lists available regions in a given monolingual language dataset.
      headers:
        app_id:
          type: string
          description: App ID Authentication Parameter
          displayName: app_id
          default: 5037d509
        app_key:
          type: string
          description: App Key Authentication Parameter
          displayName: app_key
          default: 4dc1aebaa63721f0f8e79a55e2514bc7
      responses:
        200:
          description: Successful response.
          body:
            application/json:
              type: Regions
              displayName: RegionsResults
        404:
          description: Unknown source_language.
/registers:
  /{source_language}:
    uriParameters:
      source_language:
        type: string
        description: IANA language code. Source Language.
        displayName: source_language
        enum:
        - en
        - es
        - lv
        - nso
        - ro
        - zu
    /{target_language}:
      uriParameters:
        target_language:
          type: string
          description: IANA language code. Target Language.
          displayName: target_language
          enum:
          - es
          - en
          - lv
          - nso
          - ro
          - zu
      get:
        description: |
          Returns a list of the available registers for a given bilingual language dataset.
        displayName: Lists available registers in a given bilingual language dataset.
        headers:
          app_id:
            type: string
            description: App ID Authentication Parameter
            displayName: app_id
            default: 5037d509
          app_key:
            type: string
            description: App Key Authentication Parameter
            displayName: app_key
            default: 4dc1aebaa63721f0f8e79a55e2514bc7
        responses:
          200:
            description: Successful response.
            body:
              application/json:
                type: Labels
                displayName: RegistersResults
          400:
            description: source_language and target_language are same.
          404:
            description: Unknown source_language and/or target_language.
          500:
            description: Internal Error. An error occourred while processing the data.
    get:
      description: |
        Returns a list of the available registers for a given monolingual language dataset.
      displayName: Lists available registers in a given monolingual language dataset.
      headers:
        app_id:
          type: string
          description: App ID Authentication Parameter
          displayName: app_id
          default: 5037d509
        app_key:
          type: string
          description: App Key Authentication Parameter
          displayName: app_key
          default: 4dc1aebaa63721f0f8e79a55e2514bc7
      responses:
        200:
          description: Successful response.
          body:
            application/json:
              type: Labels
              displayName: RegistersResults
        404:
          description: Unknown source_language.
        500:
          description: Internal Error. An error occourred while processing the data.
/search:
  /{source_lang}:
    uriParameters:
      source_lang:
        type: string
        description: IANA language code
        displayName: source_lang
        enum:
        - en
        - es
        - lv
        - hi
    /translations={target_lang}:
      uriParameters:
        target_lang:
          type: string
          description: IANA language code
          displayName: target_lang
          enum:
          - es
          - en
          - lv
          - nso
          - ro
          - zu
          - ms
          - id
          - tn
      get:
        description: "\nFind available translation results  for a search query and\
          \ language. \n\n  <div id=\"search_translation\"></div>\n"
        displayName: Find translation results for search query.
        queryParameters:
          q?:
            type: string
            description: Search string.
            displayName: q
            default: eye
          prefix?:
            type: boolean
            description: Set prefix to true if you'd like to get results only starting with search string.
            displayName: prefix
          regions?:
            type: string
            description: Filter words with specific region(s) E.g., regions=us. For now gb, us are available for en language.
            displayName: regions
          limit?:
            type: string
            description: Limit the number of results per response. Default and maximum limit is 5000.
            displayName: limit
          offset?:
            type: string
            description: Offset the start number of the result.
            displayName: offset
        headers:
          app_id:
            type: string
            description: App ID Authentication Parameter
            displayName: app_id
            default: 5037d509
          app_key:
            type: string
            description: App Key Authentication Parameter
            displayName: app_key
            default: 4dc1aebaa63721f0f8e79a55e2514bc7
        responses:
          200:
            description: Successful response.
            body:
              application/json:
                type: Wordlist
                displayName: WordlistResults
          404:
            description: |
              No entry is found matching supplied id and source_lang or filters are not recognized
          500:
            description: |
              Internal Error. An error occurred while processing the data.
    get:
      description: "\nRetrieve available results for a search query and language.\
        \ \n\n  <div id=\"search\"></div>\n"
      displayName: Find results for search query.
      queryParameters:
        q?:
          type: string
          description: Search string.
          displayName: q
          default: eye
        prefix?:
          type: boolean
          description: Set prefix to true if you'd like to get results only starting with search string.
          displayName: prefix
        regions?:
          type: string
          description: Filter words with specific region(s) E.g., regions=us. For now gb, us are available for en language.
          displayName: regions
        limit?:
          type: string
          description: Limit the number of results per response. Default and maximum limit is 5000.
          displayName: limit
        offset?:
          type: string
          description: Offset the start number of the result.
          displayName: offset
      headers:
        app_id:
          type: string
          description: App ID Authentication Parameter
          displayName: app_id
          default: 5037d509
        app_key:
          type: string
          description: App Key Authentication Parameter
          displayName: app_key
          default: 4dc1aebaa63721f0f8e79a55e2514bc7
      responses:
        200:
          description: Successful response.
          body:
            application/json:
              type: Wordlist
              displayName: WordlistResults
        404:
          description: |
            No entry is found matching supplied id and source_lang or filters are not recognized
        500:
          description: |
            Internal Error. An error occurred while processing the data.
/wordlist:
  /{source_lang}:
    uriParameters:
      source_lang:
        type: string
        description: IANA language code
        displayName: source_lang
        enum:
        - en
        - es
        - lv
        - hi
    /{filters_advanced}:
      uriParameters:
        filters_advanced:
          type: string
          description: 'Semicolon separated list of wordlist parameters, presented
            as value pairs: LexicalCategory, domains, regions, registers. Parameters
            can take comma separated list of values. E.g., lexicalCategory=noun,adjective;domains=sport'
          displayName: filters_advanced
          default: registers=Rare;domains=Art
      get:
        description: "Advanced options for retrieving wordlist - exclude filter, filter\
          \ by word length or match by substring (prefix). \n\n  <div id=\"wordlist_advanced\"\
          ></div>\n"
        displayName: Retrieve list of words for category with advanced options.
        queryParameters:
          exclude?:
            type: string
            description: 'Semicolon separated list of wordlist parameters to be excluded
              from response, presented as value pairs: LexicalCategory, domains, regions,
              registers. Parameters can take comma separated list of values.'
            displayName: exclude
          word_length?:
            type: string
            description: Parameter to speficy the minimum (>), exact or maximum (<) length of the words required. E.g., >5 - more than 5 chars; <4 - less than 4 chars; >5<10 - from 5 to 10 chars; 3 - exactly 3 chars.
            displayName: word_length
          prefix?:
            type: string
            description: Filter words that start with prefix parameter
            displayName: prefix
            default: eye
          exact?:
            type: boolean
            description: If exact=true wordlist returns a list of entries that exactly matches the search string. Otherwise wordlist lists entries that start with prefix string.
            displayName: exact
          limit?:
            type: string
            description: Limit the number of results per response. Default and maximum limit is 5000.
            displayName: limit
          offset?:
            type: string
            description: Offset the start number of the result.
            displayName: offset
        headers:
          app_id:
            type: string
            description: App ID Authentication Parameter
            displayName: app_id
            default: 5037d509
          app_key:
            type: string
            description: App Key Authentication Parameter
            displayName: app_key
            default: 4dc1aebaa63721f0f8e79a55e2514bc7
        responses:
          200:
            description: Successful response.
            body:
              application/json:
                type: Wordlist
                displayName: WordlistResults
          400:
            description: disjoint sets of word_length values (eg <3>10); filter has no values; total number of filters > 20; filters and excludes values can not be the same; source_lang and translations can not be same; word_length conflicts with prefix length.
          404:
            description: |
              No entries is found matching supplied filters or lang or filters is not recognized.
          500:
            description: |
              Internal Error. An error occourred while processing the data.
    /{filters_basic}:
      uriParameters:
        filters_basic:
          type: string
          description: 'Semicolon separated list of wordlist parameters, presented
            as value pairs: LexicalCategory, domains, regions, registers. Parameters
            can take comma separated list of values. E.g., lexicalCategory=noun,adjective;domains=sport.'
          displayName: filters_basic
          default: registers=Rare;domains=Art
      get:
        description: "Retrieve list of words for particular domain, lexical category\
          \ register and/or region.  \n\n  <div id=\"wordlist\"></div>\n"
        displayName: Retrieve list of words for category.
        queryParameters:
          limit?:
            type: string
            description: Limit the number of results per response. Default and maximum limit is 5000.
            displayName: limit
          offset?:
            type: string
            description: Offset the start number of the result.
            displayName: offset
        headers:
          app_id:
            type: string
            description: App ID Authentication Parameter
            displayName: app_id
            default: 5037d509
          app_key:
            type: string
            description: App Key Authentication Parameter
            displayName: app_key
            default: 4dc1aebaa63721f0f8e79a55e2514bc7
        responses:
          200:
            description: Successful response.
            body:
              application/json:
                type: Wordlist
                displayName: WordlistResults
          400:
            description: filter has no values; total number of filters > 20.
          404:
            description: |
              No entries is found matching supplied filters or lang or filters is not recognized.
          500:
            description: |
              Internal Error. An error occourred while processing the data.
