#%RAML 1.0
title: PasswordUtility.Web
version: v1
baseUri: passwordutility.net:80
description: Validate and generate passwords using open source tools
uses:
  commons: https://raw.githubusercontent.com/apiregistry/commons/master/commons.raml
  extras: https://raw.githubusercontent.com/apiregistry/typesExtras/master/typeExtras.raml
types:
  Object:
    type: object
/api:
  /password:
    /generate:
      post:
        queryParameters:
          length:
            type: integer
            displayName: length
            format: int32
          upperCase?:
            type: boolean
            displayName: upperCase
          digits?:
            type: boolean
            displayName: digits
          specialCharacters?:
            type: boolean
            displayName: specialCharacters
        responses:
          200:
            description: OK
            body:
              application/json:
                type: Object
              text/json:
                type: Object
              application/xml:
                type: Object
              text/xml:
                type: Object
    /validate:
      post:
        queryParameters:
          password:
            type: string
            displayName: password
        responses:
          200:
            description: OK
            body:
              application/json:
                type: Object
              text/json:
                type: Object
              application/xml:
                type: Object
              text/xml:
                type: Object
